### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by fengerzh** [abetlen/llama-cpp-python#106]
Seems could not find AVX.

```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting llama-cpp-python
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1b/ea/3f2aff10fd7195c6bc8c52375d9ff027a551151569c50e0d47581b14b7c1/llama_cpp_python-0.1.36.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 1.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typing-extensions>=4.5.0 (from llama-cpp-python)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/31/25/5abcd82372d3d4a3932e1fa8c3dbf9efac10cc7c0d16e78467460571b404/typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [130 lines of output]


      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 7.5.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.6s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-lt0icfg9/llama-cpp-python_84ffb3b3afdd4f84aacc9ffd49b27f9e/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
                                              _mm256_set_epi8
      ggml.c:2815:40: 错误：‘_mm256_mul_ps’的第 1 个实参类型不兼容
      In file included from /usr/local/lib/gcc/x86_64-pc-linux-gnu/7.5.0/include/immintrin.h:41:0,
                       from ggml.c:189:
      /usr/local/lib/gcc/x86_64-pc-linux-gnu/7.5.0/include/avxintrin.h:318:1: 附注：需要类型‘__m256 {或称 __vector(8) float}’，但实参的类型为‘int’
       _mm256_mul_ps (__m256 __A, __m256 __B)
       ^~~~~~~~~~~~~
      ggml.c:2819:22: 警告：implicit declaration of function ‘_mm256_set_m128i’; did you mean ‘_mm256_set_epi8’? [-Wimplicit-function-declaration]
               __m256i bx = _mm256_set_m128i(bx1, bx0);
                            ^~~~~~~~~~~~~~~~
                            _mm256_set_epi8
      ggml.c:2819:22: 错误：用‘int’初始化‘__m256i {或称 __vector(4) long long int}’时类型不兼容
      在文件作用域：
      ggml.c:1082:13: 警告：‘quantize_row_q4_2_reference’ defined but not used [-Wunused-function]
       static void quantize_row_q4_2_reference(const float * restrict x, block_q4_2 * restrict y, int k) {
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      make: *** [Makefile:153：ggml.o] 错误 1
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-ezkhm3ky/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-ezkhm3ky/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 691, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-ezkhm3ky/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 736, in make_impl
          raise SKBuildError(msg)

      An error occurred while building with CMake.
        Command:
          /tmp/pip-build-env-ezkhm3ky/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /tmp/pip-install-lt0icfg9/llama-cpp-python_84ffb3b3afdd4f84aacc9ffd49b27f9e
        Working directory:
          /tmp/pip-install-lt0icfg9/llama-cpp-python_84ffb3b3afdd4f84aacc9ffd49b27f9e/_skbuild/linux-x86_64-3.9/cmake-build
      Please check the install target is valid and see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

**Comment by JiwenZ** [comment]
upgrade gcc to 11 will fix this

**Comment by fengerzh** [comment]
Yes, gcc 11 solved problem. Thank you!

**Comment by sharansabi** [comment]
How did you upgrade to gcc-11 safely? I still have gcc 7.5 and I get the same error as you got above
1

**Comment by fengerzh** [comment]
> How did you upgrade to gcc-11 safely? I still have gcc 7.5 and I get the same error as you got above!

I don't know other os, but for centos7, it's simple:

```
yum install centos-release-scl
yum install devtoolset-11-gcc*
scl enable devtoolset-11 bash
```

it will be installed in `/opt/rh/devtoolset-11`

**Comment by rahulrajpl** [comment]
installing gcc-11 didn't resolve the issue in ubuntu 22.04

Can someone please provide detailed requisites for successful installation?

**Comment by gjmulder** [comment]
> installing gcc-11 didn't resolve the issue in ubuntu 22.04

Please open a new issue and use the issue template so we can better understand your problem.
