### ISSUE TITLE
Problem with ChatCompletionMessage when using cuBLAS and Mistral.

### ISSUE THREAD

**Issue by hexagonsix** [abetlen/llama-cpp-python#1144]
# Expected Behavior

I expected the LM to output something, specifically output something into a database then output the result of the database entry, basically just a chat with a database in the middle. I was trying to use ChatCompletionMessage to pre-process messages so they'd go into a database neatly (following instructions from someone else). This code works when llama-cpp-python is compiled without cuBLAS. But with cuBLAS it loads the model to GPU memory like it should, it only crashes when it tries to generate a response to my input, or possibly when it gets the input. It might be Mistral specific, but I had no issue using the same Mistral model when llama-cpp-python was compiled without cuBLAS which is why I think it's a bug.

# Current Behavior

It failed to run giving me an undefined error related to jinja2 which my AI tells me is related to storing data in XML and HTML files and stuff, I'm assuming it's handling the instruction format or something, but I'm too noob to really know. Here is the error:

```
Traceback (most recent call last):
  File "C:\LLM\chat.py", line 97, in <module>
    handle_message(message_content, author_name)
  File "C:\LLM\chat.py", line 78, in handle_message
    for token in completion:
  File "C:\LLM\llama.py", line 68, in chat_completion
    completion = self.model.create_chat_completion(chat_messages, stream=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\LLM\envs\Lib\site-packages\llama_cpp\llama.py", line 1523, in create_chat_completion
    return handler(
           ^^^^^^^^
  File "C:\LLM\envs\Lib\site-packages\llama_cpp\llama_chat_format.py", line 322, in chat_completion_handler
    result = chat_formatter(
             ^^^^^^^^^^^^^^^
  File "C:\LLM\envs\Lib\site-packages\llama_cpp\llama_chat_format.py", line 195, in __call__
    prompt = self._environment.render(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\LLM\envs\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\LLM\envs\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "C:\LLM\envs\Lib\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'raise_exception' is undefined
```

The line it traces back to is just a very simple chat prompt at the end of my script I'm using for testing and shouldn't be relevant, it looks like this:
```
try:
    while True:
        message_content = input("Enter your message: ")
        author_name = "User"
        handle_message(message_content, author_name)
finally:
    # Delete the chat from the database
    DB.delete_all_chats()
```
The problem part seems to be here:
`completion = self.model.create_chat_completion(chat_messages, stream=True)` 

# Environment and Context

Conda environment using python 3.12, llama-cpp-python is installed like this:

$env:FORCE_CMAKE='1'; $env:CMAKE_ARGS='-DLLAMA_CUBLAS=on'
pip3 install llama-cpp-python --no-cache-dir --verbose

PyTorch like this:
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

I also have these packages installed using pip in the environment:
python-dotenv
pymongo
pydantic<2.0

* Physical (or virtual) hardware you are using:

RTX 4090, i9-13900K, lots of memory.

* Operating System:

Windows 11

**Comment by abetlen** [comment]
Hey @hexagonsix can I ask which model you're using?

The issue is that your model includes a jinja2 chat template used to generate the prompt, some chat templates will call a `raise_exception` function if you're conversation is in the incorrect format.

**Comment by abetlen** [comment]
I just pushed a fix for more descriptive jinja2 errors however this is the template used by mistral-instruct:


```
"{{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token + ' ' }}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}"
```

There are 2 cases where raise_exception is called
- Trying to use a role other than assistant or user (system messages aren't supported by this model)
- Not calling it in the `user/assistant/user/assistant` order

**Comment by hexagonsix** [comment]
Yes, it's the Mistral-7B-Instruct-v0.2, the gguf version from TheBloke. 

I'm pretty sure I'm doing both of those things right, but I am kind of new at this. I'm definitely using the assistant and user roles though. There might be a problem with the order, didn't think there was since it's logging fine in the database as user/assistant/user/assistant, but it is acting kind of weird sometimes so I'm looking into it.

Sorry it took so long to respond, I actually downgraded to llama-cpp-python version 0.2.33 and it works fine in that version, at least it doesn't give me any errors, so I kind of forgot about it. Thanks for the update though, appreciate all the great work you guys do.

**Comment by hockeybro12** [comment]
@abetlen I had the same issue, downgraded to 0.2.33 like @hexagonsix suggested and it worked for me. Only that particular model (mistal-7B-instruct-v0.1.gguf), others work fine. 

I'm using it with the server, like so, and I get an empty response on the latest version (I had upgraded on Friday):
```
import openai
openai.api_base = "http://128.10.12.201:47526/v1"

given_input = "The world is"

openai.api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
message_list = []

message_list.append({"role": "user", "content": given_input})


given_response = openai.ChatCompletion.create(model='davinci', temperature=0.0, messages=message_list, top_p=1, max_tokens=1000)["choices"][0]["message"]['content'].replace('"', '')
print(given_response)
```
