### ISSUE TITLE
I'm loading a gguf but llama-python-cpp says "is it really a GGML file" ???

### ISSUE THREAD

**Issue by takosalad** [abetlen/llama-cpp-python#1191]
Installed llama_cpp_python-0.2.43.tar.gz via
CMAKE_ARGS="-DLLAMA_CUBLAS=ON -DCMAKE_CUDA_COMPILER=/opt/cuda/bin/nvcc -DTCNN_CUDA_ARCHITECTURES=61" pip install llama-cpp-python

llm = Llama(model_path="/home/takosalad/llama/models/nous-capybara-3b-v1.9.q5_k_m.gguf",
            n_gpu_layers=63, n_threads=6, n_ctx=3584, n_batch=512, verbose=True),

ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9
llama.cpp: loading model from /home/takosalad/llama/models/nous-capybara-3b-v1.9.q5_k_m.gguf
error loading model: unknown (magic, version) combination: 46554747, 00000003; is this really a GGML file?
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/home/takosalad/llama/./8ball.py", line 35, in <module>
    llm = Llama(model_path="/home/takosalad/llama/models/nous-capybara-3b-v1.9.q5_k_m.gguf",
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/takosalad/.local/lib/python3.11/site-packages/llama_cpp/llama.py", line 305, in __init__
    assert self.model is not None
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception ignored in: <function Llama.__del__ at 0x7e4db408bd80>
Traceback (most recent call last):
  File "/home/takosalad/.local/lib/python3.11/site-packages/llama_cpp/llama.py", line 1502, in __del__
    if self.ctx is not None:
       ^^^^^^^^
AttributeError: 'Llama' object has no attribute 'ctx'

**Comment by takosalad** [comment]
I was able to fix this by setting an environment variable as someone on stackoverflow found out, LLAMA_CPP_LIB
