### ISSUE TITLE
 ValueError: Attempt to split tensors that exceed maximum supported devices. Current LLAMA_MAX_DEVICES=1

### ISSUE THREAD

**Issue by thiner** [abetlen/llama-cpp-python#1198]
I am not sure whether this is a bug of llama-cpp-python, because I searched history issues, and there are similar issues were marked as fixed. But I can't find any clue from those issues.
I built the latest code into docker image, with `docker/cuda_simple/Dockerfile`. I have two GPUs on the server, but the container failed to startup with error message as below:
```
 Traceback (most recent call last):

   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main

     return _run_code(code, main_globals, None,

   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code

     exec(code, run_globals)

   File "/usr/local/lib/python3.10/dist-packages/llama_cpp/server/__main__.py", line 88, in <module>

     main()

   File "/usr/local/lib/python3.10/dist-packages/llama_cpp/server/__main__.py", line 74, in main

     app = create_app(

   File "/usr/local/lib/python3.10/dist-packages/llama_cpp/server/app.py", line 133, in create_app

     set_llama_proxy(model_settings=model_settings)

   File "/usr/local/lib/python3.10/dist-packages/llama_cpp/server/app.py", line 70, in set_llama_proxy

     _llama_proxy = LlamaProxy(models=model_settings)

   File "/usr/local/lib/python3.10/dist-packages/llama_cpp/server/model.py", line 30, in __init__

     self._current_model = self.load_llama_from_model_settings(

   File "/usr/local/lib/python3.10/dist-packages/llama_cpp/server/model.py", line 119, in load_llama_from_model_settings

     _model = llama_cpp.Llama(

   File "/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py", line 191, in __init__

     raise ValueError(

 ValueError: Attempt to split tensors that exceed maximum supported devices. Current LLAMA_MAX_DEVICES=1
```

My command to start the container:
```
python3 -m  llama_cpp.server --model /opt/models/openhermes-mixtral-8x7b.Q5_K_M.gguf --chat_format  llama-2 --tensor_split [0.5 0.5]  --n_gpu_layers -1
```

I searched documentation and code, couldn't find any way to set a value for the `LLAMA_MAX_DEVICES`.

**Comment by thiner** [comment]
OK, this is duplicated with #1166
