### ISSUE TITLE
AttributeError: module 'llama_cpp.llama_cpp' has no attribute 'c_uint8'

### ISSUE THREAD

**Issue by goldyfruit** [abetlen/llama-cpp-python#1213]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Current Behavior

```
AttributeError: module 'llama_cpp.llama_cpp' has no attribute 'c_uint8'
```

# Environment and Context

Everything was fine with version 0.2.45 but since I updated this morning to the latest version I got the trace when using the chat completion.

```
Llama._create_completion: cache miss
Llama.generate: prefix-match hit
llama_print_timings:        load time =     345.45 ms
llama_print_timings:      sample time =     354.10 ms /   216 runs   (    1.64 ms per token,   610.00 tokens per second)
llama_print_timings: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_print_timings:        eval time =    6525.13 ms /   216 runs   (   30.21 ms per token,    33.10 tokens per second)
llama_print_timings:       total time =    9308.07 ms /   217 tokens
Llama._create_completion: cache save
Llama.save_state: saving llama state
Llama.save_state: got state size: 334057508
Exception: module 'llama_cpp.llama_cpp' has no attribute 'c_uint8'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/server/errors.py", line 170, in custom_route_handler
    response = await original_route_handler(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/server/app.py", line 365, in create_chat_completion
    ] = await run_in_threadpool(llama.create_chat_completion, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py", line 1635, in create_chat_completion
    return handler(
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/llama_chat_format.py", line 351, in chat_completion_handler
    completion_or_chunks = llama.create_completion(
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py", line 1473, in create_completion
    completion: Completion = next(completion_or_chunks)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py", line 1289, in _create_completion
    self.cache[prompt_tokens + completion_tokens] = self.save_state()
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py", line 1792, in save_state
    llama_state = (llama_cpp.c_uint8 * int(state_size))()
AttributeError: module 'llama_cpp.llama_cpp' has no attribute 'c_uint8'
INFO:     10.233.81.108:38476 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
```

**Comment by goldyfruit** [comment]
Thanks @abetlen
