### ISSUE TITLE
latest build 0.2.56 breaks SYCL build

### ISSUE THREAD

**Issue by xtremehpx** [abetlen/llama-cpp-python#1275]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [0.2.56 ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X ] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [ X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X ] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

After following the steps to install llama_cpp_python + SYCL, the application should work and can run on Intel GPU.

# Current Behavior

- The installation guide in the ReadMe is not sufficient for SYCL to be enabled, at least for Windows. Instead, user should follow the steps in llama.cpp SYCL ReadMe.  The tweaked installation was successful. 

- The compiled and installed version will not run. It throws below error:

- Revert back to version 0.2.44, then it works. Thanks to https://github.com/abetlen/llama-cpp-python/issues/1197

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

Intel MTL Ultra 7 155H + ARC GPU

* Operating System, e.g. for Linux:

Windows 11

```
$ python3 --version 
3.10, 3.12

$ make --version 
GNU Make 4.4 Built for x86_64-w64-mingw32

$ g++ --version
gcc.exe (GCC) 13.2.0

```

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. step 1 create a python virtual environment 
2. step 2 following llama_cpp_python installation instructions for SYCL
3. step 3 start python environment
4. step 4 run : from llama_cpp import llama

# Failure Logs

```python
C:\repo\llama_cpp_python\test_llamacpp.py:2: SyntaxWarning: invalid escape sequence '\l'
  llm = Llama(model_path="C:\llm\models\mistral-7b-instruct-v0.2.Q4_K_M.gguf", n_gpu_layer=20, n_ctx=1024)
Traceback (most recent call last):
  File "C:\repo\llama_cpp_python\.venv\Lib\site-packages\llama_cpp\llama_cpp.py", line 70, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\repo\llama_cpp_python\.venv\Lib\site-packages\llama_cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

  File "C:\repo\llama_cpp_python\test_llamacpp.py", line 1, in <module>
    from llama_cpp import Llama
  File "C:\repo\llama_cpp_python\.venv\Lib\site-packages\llama_cpp\__init__.py", line 1, in <module>    from .llama_cpp import *
  File "C:\repo\llama_cpp_python\.venv\Lib\site-packages\llama_cpp\llama_cpp.py", line 83, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\repo\llama_cpp_python\.venv\Lib\site-packages\llama_cpp\llama_cpp.py", line 72, in _load_shared_library       
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library 'C:\repo\llama_cpp_python\.venv\Lib\site-packages\llama_cpp\llama.dll': Could not find module 'C:\repo\llama_cpp_python\.venv\Lib\site-packages\llama_cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

# What I have tried

1. I was able to compile llama.cpp without issue. So I tried to copy over the llama.dll to replace the one created here. But it didn't work. 
2. the only way it works is to revert back to an older version. 0.2.44 worked. I have not tried other versions.

**Comment by xtremehpx** [comment]
Actually it turns out I need to activate the oneAPI environment, otherwise, this will not run.
