### ISSUE TITLE
ValueError: Failed to create llama_context

### ISSUE THREAD

**Issue by Isaakkamau** [abetlen/llama-cpp-python#1304]
(yuna2) (base) adm@Adms-MacBook-Pro yuna-ai % python index.py
ggml_metal_init: error: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:3:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
" UserInfo={NSLocalizedDescription=program_source:3:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
}
llama_new_context_with_model: failed to initialize Metal backend
Traceback (most recent call last):
  File "/Users/adm/Desktop/yuna-ai/index.py", line 171, in <module>
    yuna_server = YunaServer()
                  ^^^^^^^^^^^^
  File "/Users/adm/Desktop/yuna-ai/index.py", line 33, in __init__
    self.chat_generator = ChatGenerator(self.config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adm/Desktop/yuna-ai/lib/generate.py", line 11, in __init__
    self.model = Llama(
                 ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/llama_cpp/llama.py", line 328, in __init__
    self._ctx = _LlamaContext(
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/llama_cpp/_internals.py", line 265, in __init__
    raise ValueError("Failed to create llama_context")
ValueError: Failed to create llama_context
<img width="585" alt="Screen Shot 2024-03-25 at 23 43 18" src="https://github.com/abetlen/llama-cpp-python/assets/95031660/922cb7a2-1d05-42c4-b45a-4b04154cac4c">

**Comment by JackyCCK2126** [comment]
Maybe you need to reinstall with 

> `CMAKE_ARGS="-DLLAMA_METAL_EMBED_LIBRARY=ON -DLLAMA_METAL=on" pip3 install -U --force-reinstall llama-cpp-python --no-cache-dir`

Answer from: https://github.com/abetlen/llama-cpp-python/issues/1285#issuecomment-2007778703

**Comment by yukiarimo** [comment]
Hey, @JackyCCK2126! I'm having the same issue, and now it works! Thanks, but what was the problem with?

Also, is there any workaround to speed up the generation on the M1?

**Comment by JackyCCK2126** [comment]
@yukiarimo I don't know much about M1. But in general, you can offload more layers in GPU and lower the context size when initializing the LLama class by setting `n_gpt_layers` and `n_ctx`. (`top_p` and `top_k` may also affect a bit of speed) If it is still too slow, you can choose a smaller model.

However, if your prompt is not too long, it should have around 7 to 12 tokens per second, which is enough for me.

**Comment by JackyCCK2126** [comment]
@yukiarimo If you found a speed-up solution, please let me know. XD

**Comment by Spider-netizen** [comment]
> Maybe you need to reinstall llama-cpp-python with the following command:
> 
> > CMAKE_ARGS="-DLLAMA_METAL_EMBED_LIBRARY=ON -DLLAMA_METAL=on" pip3 install -U --force-reinstall llama-cpp-python --no-cache-dir
> 
> Answer from: [#1285 (comment)](https://github.com/abetlen/llama-cpp-python/issues/1285#issuecomment-2007778703)

Doesn't seem to solve it for me... Do you happen to know if I'm missing something?

That's the end of the traceback:


<img width="762" alt="Screen Shot 2024-04-17 at 23 45 45" src="https://github.com/abetlen/llama-cpp-python/assets/49787838/01d62efd-a556-4d94-a475-115779e41b5b">

**Comment by ScofieldYeh** [comment]
> > Maybe you need to reinstall llama-cpp-python with the following command:
> > > CMAKE_ARGS="-DLLAMA_METAL_EMBED_LIBRARY=ON -DLLAMA_METAL=on" pip3 install -U --force-reinstall llama-cpp-python --no-cache-dir
> > 
> > 
> > Answer from: [#1285 (comment)](https://github.com/abetlen/llama-cpp-python/issues/1285#issuecomment-2007778703)
> 
> Doesn't seem to solve it for me... Do you happen to know if I'm missing something?
> 
> That's the end of the traceback:
> 
> <img alt="Screen Shot 2024-04-17 at 23 45 45" width="762" src="https://private-user-images.githubusercontent.com/49787838/323374026-01d62efd-a556-4d94-a475-115779e41b5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjU3MDAsIm5iZiI6MTcxNzI2NTQwMCwicGF0aCI6Ii80OTc4NzgzOC8zMjMzNzQwMjYtMDFkNjJlZmQtYTU1Ni00ZDk0LWE0NzUtMTE1Nzc5ZTQxYjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE4MTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YWZjNjZjZDIxZjcxMGQ1ZDUxMWY2ODI2MGY4MzY3ZmU3MTY3YmJkNTY2ZWY4NDU5ZmVlNGRkNjZlMzEzNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xYcPcutbA5hSpjGRWNJz0RoLZIw4dYFz3co33r1-5is">

I have the same result too. It failed to create llama_context.

**Comment by JackyCCK2126** [comment]
> > > Maybe you need to reinstall llama-cpp-python with the following command:
> > > > CMAKE_ARGS="-DLLAMA_METAL_EMBED_LIBRARY=ON -DLLAMA_METAL=on" pip3 install -U --force-reinstall llama-cpp-python --no-cache-dir
> > > 
> > > 
> > > Answer from: [#1285 (comment)](https://github.com/abetlen/llama-cpp-python/issues/1285#issuecomment-2007778703)
> > 
> > 
> > Doesn't seem to solve it for me... Do you happen to know if I'm missing something?
> > That's the end of the traceback:
> > <img alt="Screen Shot 2024-04-17 at 23 45 45" width="762" src="https://private-user-images.githubusercontent.com/49787838/323374026-01d62efd-a556-4d94-a475-115779e41b5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjU3MDAsIm5iZiI6MTcxNzI2NTQwMCwicGF0aCI6Ii80OTc4NzgzOC8zMjMzNzQwMjYtMDFkNjJlZmQtYTU1Ni00ZDk0LWE0NzUtMTE1Nzc5ZTQxYjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE4MTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YWZjNjZjZDIxZjcxMGQ1ZDUxMWY2ODI2MGY4MzY3ZmU3MTY3YmJkNTY2ZWY4NDU5ZmVlNGRkNjZlMzEzNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xYcPcutbA5hSpjGRWNJz0RoLZIw4dYFz3co33r1-5is">
> 
> I have the same result too. It failed to create llama_context. I was wondering to why need to set DLLAMA_METAL=on? I think METAL is for Macbook but I was running llama.cpp on Windows PC.

Yes. Metal is only for Apple's products.

**Comment by efwfe** [comment]
Running on m3-max chip has the same error. but llama-cpp is working fine.
```

program_source:9112:5: error: taking address of function is not allowed
    impl_fn(args, src0, src1, dst, shmem, tgpig, tiisg, sgitg);
    ^
program_source:9206:99: note: in instantiation of function template specialization 'mmv_fn<&kernel_mul_mv_iq4_nl_f32_impl>' requested here
template [[host_name("kernel_mul_mv_id_iq4_nl_f32")]]  kernel kernel_mul_mv_id_t kernel_mul_mv_id<mmv_fn<kernel_mul_mv_iq4_nl_f32_impl <N_R0_IQ4_NL,  N_SG_IQ4_NL,  N_SIMDWIDTH>>>;
                                                                                                  ^
program_source:9112:5: error: taking address of function is not allowed
    impl_fn(args, src0, src1, dst, shmem, tgpig, tiisg, sgitg);
    ^
program_source:9207:99: note: in instantiation of function template specialization 'mmv_fn<&kernel_mul_mv_iq4_xs_f32_impl>' requested here
template [[host_name("kernel_mul_mv_id_iq4_xs_f32")]]  kernel kernel_mul_mv_id_t kernel_mul_mv_id<mmv_fn<kernel_mul_mv_iq4_xs_f32_impl <N_R0_IQ4_XS,  N_SG_IQ4_XS,  N_SIMDWIDTH>>>;
                                                                                                  ^
}
ggml_metal_init: error: metal library is nil
ggml_backend_metal_device_init: error: failed to allocate context
whisper_backend_init_gpu: failed to initialize Metal backend
whisper_backend_init: using BLAS backend
ggml_metal_init: error: metal library is nil
ggml_backend_metal_device_init: error: failed to allocate context
whisper_backend_init_gpu: failed to initialize Metal backend
```

**Comment by tellsiddh** [comment]
> Im trying this on AWS Lambda and EC2, in both cases I am getting: "Failed to create llama_context". Any fix for that ?

@aklacar1  Try reducing the context length, worked for me. Changed it to a very low value - 60000 for a 128k context model on a lambda
