### ISSUE TITLE
Negative Temperature values can not be provided with OpenAI compatible API, due to restriction in FastAPI models.

### ISSUE THREAD

**Issue by SyomaKiss** [abetlen/llama-cpp-python#1384]
[This line](https://github.com/abetlen/llama-cpp-python/blob/173ebc78782b2eaed40b3b29989502cb6ecdea44/llama_cpp/server/types.py#L21C5-L21C7) here ensures that Temperature values are in range [0,2]
```python
temperature_field = Field(
    default=0.8,
    ge=0.0,
    le=2.0,
    description="Adjust the randomness of the generated text.\n\n"
    + "Temperature is a hyperparameter that controls the randomness of the generated text. It affects the probability distribution of the model's output tokens. A higher temperature (e.g., 1.5) makes the output more random and creative, while a lower temperature (e.g., 0.5) makes the output more focused, deterministic, and conservative. The default value is 0.8, which provides a balance between randomness and determinism. At the extreme, a temperature of 0 will always pick the most likely next token, leading to identical outputs in each run.",
)
```

At the same time temp values less than 0 are expected [in _LlamaSamplingContext](https://github.com/abetlen/llama-cpp-python/blob/173ebc78782b2eaed40b3b29989502cb6ecdea44/llama_cpp/_internals.py#L765).
```python
if self.params.temp < 0:
            ctx_main.sample_softmax(token_data_array)
            id = token_data_array.candidates_data["id"][0]
```
I suppose that maximum reproducibility of generation results is only possible with temp<0 values, and at the same time I would like to run OpenAI compatible web server for convenience.

**Comment by abetlen** [comment]
@SyomaKiss I'll remove both the lower and upper limits, really they're unnecessary contraints on users, thanks for pointing this out, cheers!

**Comment by SyomaKiss** [comment]
Using the server with `llm = ChatOpenAI(base_url="url", api_key="key", temperature=-1,)` result in error. Tested with llama-2 and llama-3 models.
```
Llama.generate: prefix-match hit
Exception: argument 2: TypeError: wrong type
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/server/app.py", line 462, in create_chat_completion
    ] = await run_in_threadpool(llama.create_chat_completion, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py", line 1658, in create_chat_completion
    return handler(
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/llama_chat_format.py", line 602, in chat_completion_handler
    completion_or_chunks = llama.create_completion(
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py", line 1494, in create_completion
    completion: Completion = next(completion_or_chunks)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py", line 1038, in _create_completion
    if llama_cpp.llama_token_is_eog(self._model.model, token):
ctypes.ArgumentError: argument 2: TypeError: wrong type
INFO:     100.95.229.30:58558 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
```
