### ISSUE TITLE
"llama.cpp error: 'error loading model architecture: unknown model architecture: 'deepseek2'

### ISSUE THREAD

**Issue by ZeroCool22** [abetlen/llama-cpp-python#1556]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ ] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [ ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ ] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

{
  "title": "Failed to load model",
  "cause": "llama.cpp error: 'error loading model architecture: unknown model architecture: 'deepseek2''",
  "errorData": {
    "n_ctx": 8192,
    "n_batch": 512,
    "n_gpu_layers": 31
  },
  "data": {
    "memory": {
      "ram_capacity": "31.91 GB",
      "ram_unused": "26.74 GB"
    },
    "gpu": {
      "gpu_names": [
        "NVIDIA GeForce GTX 1080 Ti"
      ],
      "vram_recommended_capacity": "11.00 GB",
      "vram_unused": "9.98 GB"
    },
    "os": {
      "platform": "win32",
      "version": "10.0.19045",
      "supports_avx2": true
    },
    "app": {
      "version": "0.2.24",
      "downloadsDir": "C:\\Users\\ZeroCool22\\.cache\\lm-studio\\models"
    },
    "model": {}
  }
}```

**Comment by ohmerhe** [comment]
+1

**Comment by coded-aesthetics** [comment]
+1

**Comment by justDeek** [comment]
I fixed it by updating Ollama (-> start the Ollama executable, right-click the icon in the notification area and click on 'restart to update'; or just reinstall Ollama).

**Comment by ZeroCool22** [comment]
I don't use Ollama at all, don't need that if i use LMS.

**Comment by AaronCodesPython** [comment]
I have the same error using, LM Studio 0.2.27, so it seems that this is an LMS problem.

**Comment by LeadhuntAI** [comment]
same issue here.. sad, wanted to test it finally, hope we will get an update for that soon!

**Comment by holchan** [comment]
Same

`llama_model_load: error loading model: error loading model architecture: unknown model architecture: 'deepseek2'
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/llama_cpp/server/__main__.py", line 97, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/llama_cpp/server/__main__.py", line 83, in main
    app = create_app(
  File "/opt/conda/lib/python3.10/site-packages/llama_cpp/server/app.py", line 147, in create_app
    set_llama_proxy(model_settings=model_settings)
  File "/opt/conda/lib/python3.10/site-packages/llama_cpp/server/app.py", line 68, in set_llama_proxy
    _llama_proxy = LlamaProxy(models=model_settings)
  File "/opt/conda/lib/python3.10/site-packages/llama_cpp/server/model.py", line 31, in __init__
    self._current_model = self.load_llama_from_model_settings(
  File "/opt/conda/lib/python3.10/site-packages/llama_cpp/server/model.py", line 217, in load_llama_from_model_settings
    _model = create_fn(
  File "/opt/conda/lib/python3.10/site-packages/llama_cpp/llama.py", line 338, in __init__
    self._model = _LlamaModel(
  File "/opt/conda/lib/python3.10/site-packages/llama_cpp/_internals.py", line 57, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: /kaggle/working/QA-Pilot/llamacpp_models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0_L.gguf`

**Comment by justchillbruh** [comment]
For anyone still experiencing this issue with LM Studio, I've been able to use the DeepSeek Coder V2 model by downgrading from 0.2.27 to 0.2.25.

**Comment by barl0g** [comment]
Updating ollama is a solution for me:

`curl -fsSL https://ollama.com/install.sh | sh`

**Comment by jabeztadesse** [comment]
+1

**Comment by jabeztadesse** [comment]
> I have the same error using, LM Studio 0.2.27, so it seems that this is an LMS problem.

Does it work in older versions? 🤔
