### ISSUE TITLE
Error When Loading Model with llama_cpp: [WinError -1073741795] Windows Error 0xc000001d

### ISSUE THREAD

**Issue by ltkien2003** [abetlen/llama-cpp-python#1660]
I am experiencing an error when trying to load a model using the llama_cpp library in a Python application packaged with PyInstaller. The error message is as follows:

Traceback (most recent call last):
  File "app.py", line 25, in <module>
  File "server\processor\text_translator.py", line 10, in __init__
  File "llama_cpp\llama.py", line 372, in __init__
  File "llama_cpp\_internals.py", line 50, in __init__
OSError: [WinError -1073741795] Windows Error 0xc000001d [17724]
Failed to execute script 'app'

This issue occurs specifically when loading the model with llama_cpp.
Could you provide guidance on how to resolve this error? Is there a known issue with llama_cpp on Windows, or could this be related to compatibility problems with PyInstaller?

**Comment by DiegoVFSAI** [comment]
no progress? get the same
