### ISSUE TITLE
FileNotFoundError: Shared library with base name 'llama' not found

### ISSUE THREAD

**Issue by HAOYON-666** [abetlen/llama-cpp-python#1764]
Traceback (most recent call last):
  File "/data/zhy/models/llama_cpp_python/model_test.py", line 1, in <module>
    from llama_cpp import Llama
  File "/data/zhy/models/llama_cpp_python/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/data/zhy/models/llama_cpp_python/llama_cpp/llama_cpp.py", line 88, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "/data/zhy/models/llama_cpp_python/llama_cpp/llama_cpp.py", line 79, in _load_shared_library
    raise FileNotFoundError(
FileNotFoundError: Shared library with base name 'llama' not found

**Comment by yanliangLi2563** [comment]
I'm also encountering the same problem on the remote host, just like the error you reported. Have you solved it?If you have solved it, could you please tell me how? Thank you very much.

**Comment by wangchuri** [comment]
I am new to this and also encountered this issue. It was resolved after installing the CUDA toolkit. You can try it
