### ISSUE TITLE
Getting error when running with docker

### ISSUE THREAD

**Issue by djaffer** [abetlen/llama-cpp-python#204]
llama.cpp: loading model from /home/user/app/ggml-gpt4-x-vicuna-13b-q5_1.bin
error loading model: unknown (magic, version) combination: 67676a74, 00000002; is this really a GGML file?
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/llama_cpp/server/__main__.py", line 46, in <module>
    app = create_app(settings=settings)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/llama_cpp/server/app.py", line 81, in create_app
    llama = llama_cpp.Llama(
            ^^^^^^^^^^^^^^^^
  File "/llama_cpp/llama.py", line 159, in __init__
    assert self.ctx is not None
           ^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by gjmulder** [comment]
There was a breaking change in the quantization format to provide a significant potential increase in performance. See #200 for more details.

[TheBloke](https://huggingface.co/TheBloke) is busily requantizing his models to support the new GGML format.

If you want to use your old models use `pip install llama-cpp-python==0.1.49` to install the old GGML model support.

**Comment by masands** [comment]
Having the same issue with v0.1.50 but latest local llama.cpp build runs fine. Should I wipe my environment and try again?

**Comment by gjmulder** [comment]
You might want to give this a try:

` LLAMA_OPENBLAS=1 pip install --force-reinstall --ignore-installed --no-cache-dir llama-cpp-python`

**Comment by MandTQuant** [comment]
That worked, thank you!

**Comment by ananthasharma** [comment]
Please use llama-cpp-python==0.1.65 with older models.

**Comment by leolivier** [comment]
Using llama-cpp-python==0.1.65 is working but why 0.1.83 (current one) isn't whether on new or old models?
I tried 0.1.83 on llama-2-13b-chat.ggmlv3.q5_1.bin from TheBloke/Llama-2-13B-chat-GGML with the issue above.
Then I tested llama-2-13b-chat.ggmlv3.q5_K_M.bin (which should use the new quant model) and I got another error (model can't be None)

**Comment by wujizhucanva** [comment]
Same issue as @leolivier when trying to import model: llama-2-7b-chat.ggmlv3.q8_0.bin

**Comment by Fanisting** [comment]
@leolivier  Similar issue, and I tried `vicuna-13b-v1.5-16k.ggmlv3.q4_1.bin` in TheBloke but got error `error loading model: unknown (magic, version) combination: 67676a74, 00000003; is this really a GGML file?`

**Comment by wujizhucanva** [comment]
> Using llama-cpp-python==0.1.65 is working but why 0.1.83 (current one) isn't whether on new or old models? I tried 0.1.83 on llama-2-13b-chat.ggmlv3.q5_1.bin from TheBloke/Llama-2-13B-chat-GGML with the issue above. Then I tested llama-2-13b-chat.ggmlv3.q5_K_M.bin (which should use the new quant model) and I got another error (model can't be None)

Hey @leolivier, seems like they are introducing a new format GGUF and instead of GGML and newer version of llama-cpp-python support GGUF.

**Comment by leolivier** [comment]
Thank you @wujizhucanva 
Nevertheless, I don't understand why you need to know the third digit of the version to know which format is supported. This doesn't sound like a good version management to me. At least, it should support the older formats...

**Comment by tkra90** [comment]
The GGML format has now been superseded by GGUF. 
As of August 21st 2023, llama.cpp no longer supports GGML models.
Either you downgrade llama-cpp-python, or use the supported GGUF formats. Here are some nice ones: [TheBloke](https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF)

**Comment by leolivier** [comment]
thank you @tkra90

**Comment by sidharth-14** [comment]
I have tried using the llama-cpp-python version 0.1.48(old), 0.1.65 and also 0.2.30(latest). Still I am facing the same error.

llama.cpp: loading model from ./llama.cpp/models/Tiny-Vicuna-1B/ggml-model-f32.gguf
error loading model: unknown (magic, version) combination: 46554747, 00000003; is this really a GGML file?
llama_init_from_file: failed to load model
Error: InnerError("Initializing llama context returned nullptr")
