### ISSUE TITLE
Cannot run the server

### ISSUE THREAD

**Issue by papipsycho** [abetlen/llama-cpp-python#209]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [c] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

the server should run 

# Current Behavior

when i try to run the server, i got this error message :

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/llama_cpp/server/__main__.py", line 53, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
model
  field required (type=value_error.missing)
```

so i the issue came from the option model i try with or without double quote ect... nothing work
python3 -m llama_cpp.server --model "models/ggml-openllama-7b-300bt-q4_0.bin"

the model is at the right place and is working if i run a simple python script

# Environment and Context

Ubuntu 22 server

* Physical (or virtual) hardware you are using, e.g. for Linux:

```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
    CPU family:          6
    Model:               79
    Thread(s) per core:  1
    Core(s) per socket:  2
    Socket(s):           1
    Stepping:            1
    BogoMIPS:            4599.99
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm
                          constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe p
                         opcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti fsgsbase bmi1 av
                         x2 smep bmi2 erms invpcid xsaveopt
Virtualization features:
  Hypervisor vendor:     Xen
  Virtualization type:   full
Caches (sum of all):
  L1d:                   64 KiB (2 instances)
  L1i:                   64 KiB (2 instances)
  L2:                    512 KiB (2 instances)
  L3:                    45 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0,1
Vulnerabilities:
  Itlb multihit:         KVM: Mitigation: VMX unsupported
  L1tf:                  Mitigation; PTE Inversion
  Mds:                   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
  Meltdown:              Mitigation; PTI
  Mmio stale data:       Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

* Operating System, e.g. for Linux:

`Linux ip-172-31-59-122 5.19.0-1024-aws #25~22.04.1-Ubuntu SMP Tue Apr 18 23:41:58 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

* SDK version, e.g. for Linux:

```
Python 3.10.6
GNU Make 4.3
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
fastapi                  0.95.1
sse-starlette            1.6.0
uvicorn                  0.22.0

```

**Comment by gjmulder** [comment]
This is just a guess, but can your please try providing the full path to the model?

**Comment by andreakiro** [comment]
#198 should hopefully fix this!

**Comment by papipsycho** [comment]
> This is just a guess, but can your please try providing the full path to the model?

So i've test with the full path, but unfortunally is not working

```
 python3 -m llama_cpp.server --model /home/ubuntu/openllama/llama.cpp/models/ggml-openllama-7b-300bt-q4_0.bin
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/llama_cpp/server/__main__.py", line 53, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
model
  field required (type=value_error.missing)
:~/openllama$ ll /home/ubuntu/openllama/llama.cpp/models/ggml-openllama-7b-300bt-q4_0.bin
-rw-rw-r-- 1 ubuntu ubuntu 4212883776 May 14 20:18 /home/ubuntu/openllama/llama.cpp/models/ggml-openllama-7b-300bt-q4_0.bin
```

**Comment by abetlen** [comment]
@papipsycho are you sure you're running the latest version?

This line seems to indicate it might be an older version of the package
```
  File "/home/ubuntu/.local/lib/python3.10/site-packages/llama_cpp/server/__main__.py", line 53, in <module>
    settings = Settings()
```

Can you try running `pip install --upgrade --force-reinstall --no-cache-dir llama-cpp-python`

**Comment by papipsycho** [comment]
@abetlen 

Ahh yes you were right, now is working correctly

Thanks a lot
