### ISSUE TITLE
No CUDA toolset found.

### ISSUE THREAD

**Issue by bfgball** [abetlen/llama-cpp-python#247]
I have C++-CMake-Tools for Windows, and CUDA toolset V11.8.89 (not sure why it says I don't have them), I also have no idea what this error means "fatal: not a git repository (or any of the parent directories): .git", below is the command I ran and the output:

```
C:\Users\MSI-NB>pip uninstall -y llama-cpp-python
Found existing installation: llama-cpp-python 0.1.51
Uninstalling llama-cpp-python-0.1.51:
  Successfully uninstalled llama-cpp-python-0.1.51

C:\Users\MSI-NB>set CMAKE_ARGS="-DLLAMA_CUBLAS=on"

C:\Users\MSI-NB>set FORCE_CMAKE=1

C:\Users\MSI-NB>pip install llama-cpp-python --no-cache-dir
```

<details>

```
Collecting llama-cpp-python
  Downloading llama_cpp_python-0.1.51.tar.gz (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 784.7 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\msi-nb\appdata\local\programs\python\python310\lib\site-packages (from llama-cpp-python) (4.5.0)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [226 lines of output]


      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
        No CMAKE_C_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Generator

          Visual Studio 17 2022

        could not find any instance of Visual Studio.



      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
        No CMAKE_C_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 16 2019 x64 v142' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
      -- The C compiler identification is MSVC 19.29.30148.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.29.30148.0
      CMake Warning (dev) at C:/Users/MSI-NB/AppData/Local/Temp/pip-build-env-hemd9i_c/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:168 (if):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at C:/Users/MSI-NB/AppData/Local/Temp/pip-build-env-hemd9i_c/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:189 (elseif):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (3.2s)
      -- Generating done (0.0s)
      -- Build files have been written to: C:/Users/MSI-NB/AppData/Local/Temp/pip-install-jlb4neib/llama-cpp-python_b4bda89d8b724d638254e1497cdd3fc8/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 16 2019 x64 v142' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\MSI-NB\AppData\Local\Temp\pip-install-jlb4neib\llama-cpp-python_b4bda89d8b724d638254e1497cdd3fc8\_skbuild\win-amd64-3.10\cmake-build
        Command:
          'C:\Users\MSI-NB\AppData\Local\Temp\pip-build-env-hemd9i_c\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\MSI-NB\AppData\Local\Temp\pip-install-jlb4neib\llama-cpp-python_b4bda89d8b724d638254e1497cdd3fc8' -G 'Visual Studio 16 2019' --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\MSI-NB\AppData\Local\Temp\pip-install-jlb4neib\llama-cpp-python_b4bda89d8b724d638254e1497cdd3fc8\_skbuild\win-amd64-3.10\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.10.6 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\MSI-NB\AppData\Local\Temp\pip-build-env-hemd9i_c\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\libs\python310.lib' '-DPython_EXECUTABLE:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\Include' '-DPython_LIBRARY:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\libs\python310.lib' '-DPython3_EXECUTABLE:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\Include' '-DPython3_LIBRARY:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\libs\python310.lib' -T v142 -A x64 '"-DLLAMA_CUBLAS=on"' -DCMAKE_BUILD_TYPE:STRING=Release -DLLAMA_CUBLAS=on

      Not searching for unused variables given on the command line.
      CMake Warning:
        Ignoring extra path from command line:

         ""-DLLAMA_CUBLAS=on""


      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
      -- The C compiler identification is MSVC 19.29.30148.0
      -- The CXX compiler identification is MSVC 19.29.30148.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Git: D:/Program Files/Git/cmd/git.exe (found version "2.38.1.windows.1")
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      CMake Warning at vendor/llama.cpp/CMakeLists.txt:105 (message):
        Git repository not found; to enable automatic generation of build info,
        make sure Git is installed and the project is a Git repository.


      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - not found
      -- Found Threads: TRUE
      -- Found CUDAToolkit: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include (found version "11.8.89")
      -- cuBLAS found
      CMake Error at C:/Users/MSI-NB/AppData/Local/Temp/pip-build-env-hemd9i_c/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:501 (message):
        No CUDA toolset found.
      Call Stack (most recent call first):
        C:/Users/MSI-NB/AppData/Local/Temp/pip-build-env-hemd9i_c/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
        C:/Users/MSI-NB/AppData/Local/Temp/pip-build-env-hemd9i_c/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
        C:/Users/MSI-NB/AppData/Local/Temp/pip-build-env-hemd9i_c/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
        vendor/llama.cpp/CMakeLists.txt:188 (enable_language)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\MSI-NB\AppData\Local\Temp\pip-build-env-hemd9i_c\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
        File "C:\Users\MSI-NB\AppData\Local\Temp\pip-build-env-hemd9i_c\overlay\Lib\site-packages\skbuild\cmaker.py", line 357, in configure
          raise SKBuildError(msg)

      An error occurred while configuring with CMake.
        Command:
          'C:\Users\MSI-NB\AppData\Local\Temp\pip-build-env-hemd9i_c\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\MSI-NB\AppData\Local\Temp\pip-install-jlb4neib\llama-cpp-python_b4bda89d8b724d638254e1497cdd3fc8' -G 'Visual Studio 16 2019' --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\MSI-NB\AppData\Local\Temp\pip-install-jlb4neib\llama-cpp-python_b4bda89d8b724d638254e1497cdd3fc8\_skbuild\win-amd64-3.10\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.10.6 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\MSI-NB\AppData\Local\Temp\pip-build-env-hemd9i_c\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\libs\python310.lib' '-DPython_EXECUTABLE:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\Include' '-DPython_LIBRARY:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\libs\python310.lib' '-DPython3_EXECUTABLE:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\Include' '-DPython3_LIBRARY:PATH=C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\libs\python310.lib' -T v142 -A x64 '"-DLLAMA_CUBLAS=on"' -DCMAKE_BUILD_TYPE:STRING=Release -DLLAMA_CUBLAS=on
        Source directory:
          C:\Users\MSI-NB\AppData\Local\Temp\pip-install-jlb4neib\llama-cpp-python_b4bda89d8b724d638254e1497cdd3fc8
        Working directory:
          C:\Users\MSI-NB\AppData\Local\Temp\pip-install-jlb4neib\llama-cpp-python_b4bda89d8b724d638254e1497cdd3fc8\_skbuild\win-amd64-3.10\cmake-build
      Please see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

```
</details>

**Comment by gjmulder** [comment]
I've seen something similar on linux where `CMake` can't find the path to `nvcc`. Can you add the path to the `bin` directory of CUDA and try the build again?

**Comment by bfgball** [comment]
Forgive me if I am not doing the right thing, I added the system environment variables but still get the exact same error.

![Capture](https://github.com/abetlen/llama-cpp-python/assets/28882497/aaa8dc8e-f87c-47eb-8792-a862902dadb2)

**Comment by gjmulder** [comment]
Looking at your output a bit more, maybe you also have a git issue:

`fatal: not a git repository (or any of the parent directories): .git`

I'm not sure why this is happening. Maybe Google for the error?

**Comment by bfgball** [comment]
I cannot find any relatable answers, I reinstalled the latest version of git and got the same error, maybe I need to run the command in a specific directory? what I been doing is just open cmd then copy/paste the command on this article https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md

```
pip uninstall -y llama-cpp-python
set CMAKE_ARGS="-DLLAMA_CUBLAS=on"
set FORCE_CMAKE=1
pip install llama-cpp-python --no-cache-dir
```

**Comment by gjmulder** [comment]
> `fatal: not a git repository (or any of the parent directories): .git`

This implies the git checkout of `llama.ccp` failed. Is the `git.exe` binary in your system path?

FYI: I don't use Windows so I'm just guessing here, sorry :man_shrugging:

**Comment by noprotocolunit** [comment]
> I cannot find any relatable answers, I reinstalled the latest version of git and got the same error, maybe I need to run the command in a specific directory? what I been doing is just open cmd then copy/paste the command on this article https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md
> 
> ```
> pip uninstall -y llama-cpp-python
> set CMAKE_ARGS="-DLLAMA_CUBLAS=on"
> set FORCE_CMAKE=1
> pip install llama-cpp-python --no-cache-dir
> ```

I had this issue and after much arguing with git and cuda, this is what worked for me:

> you just need to copy all the four files from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\extras\visual_studio_integration\MSBuildExtensions, and paste them to C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations. These paths should be changed to your own.

**Comment by gjmulder** [comment]
Any update?

**Comment by gjmulder** [comment]
Closing due to inactivity

**Comment by PenziSu** [comment]
@noprotocolunit it is worked for me. thank you. :D

**Comment by leocui9387** [comment]
> > I cannot find any relatable answers, I reinstalled the latest version of git and got the same error, maybe I need to run the command in a specific directory? what I been doing is just open cmd then copy/paste the command on this article https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md
> > ```
> > pip uninstall -y llama-cpp-python
> > set CMAKE_ARGS="-DLLAMA_CUBLAS=on"
> > set FORCE_CMAKE=1
> > pip install llama-cpp-python --no-cache-dir
> > ```
> 
> I had this issue and after much arguing with git and cuda, this is what worked for me:
> 
> > you just need to copy all the four files from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\extras\visual_studio_integration\MSBuildExtensions, and paste them to C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations. These paths should be changed to your own.
> 
> (For me, the version was v12.1 and I only have the build tools installed, so my destination directory looks like this: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\BuildCustomizations`)

I had to put files from:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\extras\visual_studio_integration\MSBuildExtensions
into:
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\BuildCustomizations
  - in the "VC" folder I had "v150", "v160", and "v170". I only tried "v170" and everything started to work for me
Slightly different but hope it helps someone.

**Comment by Anton-V-K** [comment]
The error like `No CUDA toolset found` usually means:
1. CUDA Toolset doesn't support your version of VisualStudio - older versions of CUDA Toolset aren't aware of the newer versions of VisualStudio
2. you've installed VisualStudio after CUDA Toolset
3. you have only VS BuildTools installed - they aren't supported by CUDA Toolset out-of-the-box

For the 1-st case instead of manually copying "build support scripts" (such step seems to be a legit workaround), you can specify which toolset to use, for example: `set "CMAKE_GENERATOR=Visual Studio 16 2019"`

**Comment by Mgajurel** [comment]
> > I cannot find any relatable answers, I reinstalled the latest version of git and got the same error, maybe I need to run the command in a specific directory? what I been doing is just open cmd then copy/paste the command on this article https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md
> > ```
> > pip uninstall -y llama-cpp-python
> > set CMAKE_ARGS="-DLLAMA_CUBLAS=on"
> > set FORCE_CMAKE=1
> > pip install llama-cpp-python --no-cache-dir
> > ```
> 
> I had this issue and after much arguing with git and cuda, this is what worked for me:
> 
> > you just need to copy all the four files from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\extras\visual_studio_integration\MSBuildExtensions, and paste them to C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations. These paths should be changed to your own.
> 
> (For me, the version was v12.1 and I only have the build tools installed, so my destination directory looks like this: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\BuildCustomizations`)

This worked for me. Thanks.

**Comment by kot197** [comment]
> > I cannot find any relatable answers, I reinstalled the latest version of git and got the same error, maybe I need to run the command in a specific directory? what I been doing is just open cmd then copy/paste the command on this article https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md
> > ```
> > pip uninstall -y llama-cpp-python
> > set CMAKE_ARGS="-DLLAMA_CUBLAS=on"
> > set FORCE_CMAKE=1
> > pip install llama-cpp-python --no-cache-dir
> > ```
> 
> I had this issue and after much arguing with git and cuda, this is what worked for me:
> 
> > you just need to copy all the four files from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\extras\visual_studio_integration\MSBuildExtensions, and paste them to C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations. These paths should be changed to your own.
> 
> (For me, the version was v12.1 and I only have the build tools installed, so my destination directory looks like this: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\BuildCustomizations`)

After I did this 😿 it went into infinite loop after I did pip install. 
Please, god...I've been stuck installing this for a week
Can anyone help me

**Comment by pingmehard** [comment]
> > > I cannot find any relatable answers, I reinstalled the latest version of git and got the same error, maybe I need to run the command in a specific directory? what I been doing is just open cmd then copy/paste the command on this article https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md
> > > ```
> > > pip uninstall -y llama-cpp-python
> > > set CMAKE_ARGS="-DLLAMA_CUBLAS=on"
> > > set FORCE_CMAKE=1
> > > pip install llama-cpp-python --no-cache-dir
> > > ```
> > 
> > 
> > I had this issue and after much arguing with git and cuda, this is what worked for me:
> > > you just need to copy all the four files from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\extras\visual_studio_integration\MSBuildExtensions, and paste them to C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations. These paths should be changed to your own.
> > 
> > 
> > (For me, the version was v12.1 and I only have the build tools installed, so my destination directory looks like this: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\BuildCustomizations`)
> 
> After I did this 😿 it went into infinite loop after I did pip install. Please, god...I've been stuck installing this for a week Can anyone help me

Try to check what is happening when you install llama-cpp-python. Use --verbose like this:
pip install --no-cache-dir --verbose llama-cpp-python

**Comment by mattepiu** [comment]
In llama cpp (non-python) solution is "-DCMAKE_GENERATOR_TOOLSET="cuda=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4""

**Comment by HitomiTenshi** [comment]
If you use Windows and want to compile the latest version with CUDA 12.5 Toolkit and have Visual Studio 2026 installed, you need this environment variable:

> CMAKE_ARGS="-DGGML_CUDA=ON -DCMAKE_GENERATOR_TOOLSET="cuda=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5" -DCMAKE_CUDA_ARCHITECTURES="89" -DCMAKE_CUDA_FLAGS="--allow-unsupported-compiler""

Pre-requisites:

1. Install Visual Studio, make sure to select "Desktop development with C++".
2. Install CUDA 12.5 Toolkit.
3. The setting `-DCMAKE_CUDA_ARCHITECTURES="89"` needs to be updated for your  GPU(s). If you have multiple GPUs installed with varying architectures, you can write `-DCMAKE_CUDA_ARCHITECTURES="86;89"`. Check [this site](https://developer.nvidia.com/cuda/gpus) to find out what number to put into the architectures value (without the dots). `89` is for RTX 4050 - 4090, `86` is for RTX 3050 - 3090. [Reference llama.cpp documentation here.](https://github.com/ggml-org/llama.cpp/blob/master/docs/build.md#override-compute-capability-specifications)
4. `-DCMAKE_CUDA_FLAGS="--allow-unsupported-compiler"` is necessary if you use Visual Studio 2026. If you want, you can install the older Visual Studio 2022 instead and remove this flag.

I had to add `-DCMAKE_CUDA_ARCHITECTURES` because it did not detect that I have an NVIDIA GPU installed for some reason. Getting this compiled and working was a nightmare, I literally spent hours searching through multiple documentations / issues / etc. Hope this helps someone.

Thank you @mattepiu for the `-DCMAKE_GENERATOR_TOOLSET` trick, with that there was no need to copy files around.

**Comment by dythttht** [comment]
pip install llama-cpp-python --extra-index-url [https://abetlen.github.io/llama-cpp-python/whl/cu132](https://www.google.com/url?sa=E&q=https%3A%2F%2Fabetlen.github.io%2Fllama-cpp-python%2Fwhl%2Fcu132) --force-reinstall --no-cache-dir

It is work for me, if cuda is larger than 13.
