### ISSUE TITLE
llama-cpp-python not working with latest ggmls

### ISSUE THREAD

**Issue by advaitdeshmukh** [abetlen/llama-cpp-python#255]
I was trying to use the openapi server with ggmlv3 I downloaded from(https://huggingface.co/TheBloke/Wizard-Vicuna-7B-Uncensored-GGML/tree/main) while it was working fine with ggmlv2 versions, the newer ones seem to be not compatible. Is this related to the newer version released by llama.cpp?
` C:\Users\Advait\Desktop\LLAMA Server>python -m llama_cpp.server --model models/Wizard-Vicuna-7B-Uncensored.ggmlv3.q5_0.bin`
`llama.cpp: loading model from models/Wizard-Vicuna-7B-Uncensored.ggmlv3.q5_0.bin`
`error loading model: unknown (magic, version) combination: 67676a74, 00000003; is this really a GGML file?`
`llama_init_from_file: failed to load model`
`Traceback (most recent call last):`
  `File "C:\Users\Advait\miniconda3\envs\llamanew\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Advait\miniconda3\envs\llamanew\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Advait\miniconda3\envs\llamanew\lib\site-packages\llama_cpp\server\__main__.py", line 46, in <module>
    app = create_app(settings=settings)
  File "C:\Users\Advait\miniconda3\envs\llamanew\lib\site-packages\llama_cpp\server\app.py", line 92, in create_app
    llama = llama_cpp.Llama(
  File "C:\Users\Advait\miniconda3\envs\llamanew\lib\site-packages\llama_cpp\llama.py", line 159, in __init__
    assert self.ctx is not None
AssertionError`

**Comment by gjmulder** [comment]
See #251

**Comment by gjmulder** [comment]
Closing as duplicate
