### ISSUE TITLE
 [linux] [centos7] when reinstall and upgrade llama-cpp-python ,it shows error with cmake,how to fix it

### ISSUE THREAD

**Issue by AceyKubbo** [abetlen/llama-cpp-python#345]
hey guys,my os is centos7,when reinstall and upgrade llama-cpp-python ,it shows error with cmake,how to fix it
```
 ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-9dr9_54j/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-9dr9_54j/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-9dr9_54j/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)
      
      An error occurred while building with CMake.
        Command:
          /tmp/pip-build-env-9dr9_54j/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /tmp/pip-install-s0impcv3/llama-cpp-python_55123ed92da142ad9f2df4fe097b143f
        Working directory:
          /tmp/pip-install-s0impcv3/llama-cpp-python_55123ed92da142ad9f2df4fe097b143f/_skbuild/linux-x86_64-3.10/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      
      [end of output]
```

_Originally posted by @AceyKubbo in https://github.com/abetlen/llama-cpp-python/issues/244#issuecomment-1581944556_

**Comment by gjmulder** [comment]
Did you read [closed issue](https://github.com/abetlen/llama-cpp-python/issues/106#issuecomment-1546440555)?

**Comment by AceyKubbo** [comment]
> Did you read [this closed issue](https://github.com/abetlen/llama-cpp-python/issues/106#issuecomment-1546440555)?

ok,it can't work with upgrade gcc11,but gcc12 can be work
