### ISSUE TITLE
OSError: exception: integer divide by zero

### ISSUE THREAD

**Issue by gjmulder** [abetlen/llama-cpp-python#355]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

No exception or error

# Current Behavior

```
INFO:Loading Wizard-Vicuna-30B-Uncensored.ggmlv3.q5_1.bin...
INFO:llama.cpp weights detected: D:\Models\Wizard-Vicuna-30B-Uncensored.ggmlv3.q5_1.bin

INFO:Cache capacity is 0 bytes
llama.cpp: loading model from D:\Models\Wizard-Vicuna-30B-Uncensored.ggmlv3.q5_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2400
llama_model_load_internal: n_embd     = 6656
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 52
llama_model_load_internal: n_layer    = 60
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 9 (mostly Q5_1)
llama_model_load_internal: n_ff       = 17920
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 30B
llama_model_load_internal: ggml ctx size =    0.13 MB
llama_model_load_internal: mem required  = 25573.14 MB (+ 3124.00 MB per state)
llama_model_load_internal: [cublas] offloading 0 layers to GPU
llama_model_load_internal: [cublas] total VRAM used: 0 MB
.
llama_init_from_file: kv self size  = 3656.25 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
INFO:Loaded the model in 3.16 seconds.

Starting streaming server at ws://0.0.0.0:5005/api/v1/stream
INFO:Loading the extension "gallery"...
Starting API at http://0.0.0.0:5000/api
127.0.0.1 - - [08/Jun/2023 08:41:52] "GET /api/v1/model HTTP/1.1" 200 -
Running on local URL:  http://0.0.0.0:7860

Traceback (most recent call last):
  File "D:\LLM\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "D:\LLM\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 78, in generate
    for completion_chunk in completion_chunks:
  File "D:\LLM\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 756, in _create_completion
    for token in self.generate(
  File "D:\LLM\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 591, in generate
    self.eval(tokens)
  File "D:\LLM\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 320, in eval
    return_code = llama_cpp.llama_eval(
  File "D:\LLM\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 439, in llama_eval
    return _lib.llama_eval(ctx, tokens, n_tokens, n_past, n_threads)
OSError: exception: integer divide by zero
```

# Environment and Context

Copied from https://github.com/oobabooga/text-generation-webui/issues/2576

**Comment by vinovo** [comment]
Hi what is the exact cause for this and what lines in the commit were responsible for fixing this?
