### ISSUE TITLE
[0.1.62] Can't save cache to disk

### ISSUE THREAD

**Issue by Okabintaro** [abetlen/llama-cpp-python#363]
# Expected Behavior

Using the following code I expected the disk cache to work:

```python
# Model from: https://huggingface.co/TheBloke/wizardLM-13B-1.0-GGML
model_path = "/home/oka/Downloads/WizardLM-13B-1.0.ggmlv3.q4_K_M.bin"
llm = Llama(model_path=model_path, n_threads=8)
cache = LlamaDiskCache()
llm.set_cache(cache)
llm("USER: What is the complementary color of red? ASSISTANT:", max_tokens=1024, stop=["USER:", "\n"], echo=True, temperature=0.0)
```

# Current Behavior

Unfortunately there seems to be an issue when trying to pickle the value which is of type `LlamaState`.
Here is a log with the traceback:

```
Llama._create_completion: cache save
Llama.save_state: saving llama state
Llama.save_state: got state size: 421721136
Llama.save_state: allocated state
Llama.save_state: copied llama state: 22311984
Llama.save_state: saving 22311984 bytes of llama state
LlamaDiskCache.__setitem__: called
Traceback (most recent call last):
  File "/home/oka/dev/pro/gerty_new/gerty/llm/llama.py", line 55, in <module>
    example()
  File "/home/oka/dev/pro/gerty_new/gerty/llm/llama.py", line 29, in example
    llm("USER: What is the complementary color of red? ASSISTANT:", max_tokens=1024, stop=["USER:", "\n"], echo=True, temperature=0.0)
  File "/home/oka/dev/pro/gerty_new/.venv/lib/python3.10/site-packages/llama_cpp/llama.py", line 1283, in __call__
    return self.create_completion(
  File "/home/oka/dev/pro/gerty_new/.venv/lib/python3.10/site-packages/llama_cpp/llama.py", line 1235, in create_completion
    completion: Completion = next(completion_or_chunks)  # type: ignore
  File "/home/oka/dev/pro/gerty_new/.venv/lib/python3.10/site-packages/llama_cpp/llama.py", line 1082, in _create_completion
    self.cache[prompt_tokens + completion_tokens] = self.save_state()
  File "/home/oka/dev/pro/gerty_new/.venv/lib/python3.10/site-packages/llama_cpp/llama.py", line 156, in __setitem__
    self.cache[key] = value
  File "/home/oka/dev/pro/gerty_new/.venv/lib/python3.10/site-packages/diskcache/core.py", line 823, in __setitem__
    self.set(key, value, retry=True)
  File "/home/oka/dev/pro/gerty_new/.venv/lib/python3.10/site-packages/diskcache/core.py", line 772, in set
    size, mode, filename, db_value = self._disk.store(value, read, key=key)
  File "/home/oka/dev/pro/gerty_new/.venv/lib/python3.10/site-packages/diskcache/core.py", line 221, in store
    result = pickle.dumps(value, protocol=self.pickle_protocol)
_pickle.PicklingError: Can't pickle <class 'llama_cpp.llama.c_ubyte_Array_22311984'>: attribute lookup c_ubyte_Array_22311984 on llama_cpp.llama failed
```

The RAM version of the cache works.

# Environment and Context

I am running `python v3.10.11` and `llama-cpp-python 0.1.62` on arch linux.

**Comment by LynxPDA** [comment]
I have same problem too.
Ubuntu 23.04, llama-cpp-python 0.1.62, python v3.11.
LlamaRAMCache work fine.

**Comment by Okabintaro** [comment]
I looked into the problem a bit more and found that the issue is mainly that `LLamaState` is not pickable due to `LLamaState.llama_state` being a ctypes array.

I opened up a draft PR with a quick fix, but it needs a bit more work I think: https://github.com/abetlen/llama-cpp-python/pull/370
