### ISSUE TITLE
Can't install on centos

### ISSUE THREAD

**Issue by fpena06** [abetlen/llama-cpp-python#381]
Can't install on centos. I tried with conda and venv.

`Python 3.10.10`

```
CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.9.2009 (Core)
CentOS Linux release 7.9.2009 (Core)
```

```
Collecting llama-cpp-python
  Using cached llama_cpp_python-0.1.63.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting diskcache>=5.6.1
  Using cached diskcache-5.6.1-py3-none-any.whl (45 kB)
Requirement already satisfied: numpy>=1.20.0 in /projects/academic/thapar/fpena/miniconda3/lib/python3.10/site-packages (from llama-cpp-python) (1.24.3)
Requirement already satisfied: typing-extensions>=4.5.0 in /projects/academic/thapar/fpena/miniconda3/lib/python3.10/site-packages (from llama-cpp-python) (4.6.3)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-cqd_uytp/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/tmp/pip-build-env-cqd_uytp/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 148, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/tmp/pip-build-env-cqd_uytp/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
          raise SKBuildError(msg) from err

      Problem with the CMake installation, aborting build. CMake executable is /tmp/pip-build-env-cqd_uytp/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

I even tried this method:

`pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir`

Any help is appreciated.

Thanks

**Comment by fpena06** [comment]
In can install lower version.

`
CMAKE_ARGS="-DLLAMA_OPENBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python==0.1.48
Collecting llama-cpp-python==0.1.48
  Using cached llama_cpp_python-0.1.48-cp310-cp310-linux_x86_64.whl
Requirement already satisfied: typing-extensions>=4.5.0 in /projects/academic/thapar/fpena/miniconda3/lib/python3.10/site-packages (from llama-cpp-python==0.1.48) (4.6.3)
Installing collected packages: llama-cpp-python
Successfully installed llama-cpp-python-0.1.48
`

**Comment by abetlen** [comment]
@fpena06 can you post the failed build log with the `--verbose` flag?

**Comment by fpena06** [comment]
@abetlen this is pip install -r requirements --verbose

```
Building wheels for collected packages: llama-cpp-python
  Running command Building wheel for llama-cpp-python (pyproject.toml)
  Traceback (most recent call last):
    File "/tmp/pip-build-env-45n19u0t/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "/tmp/pip-build-env-45n19u0t/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 148, in __init__
      self.cmake_version = get_cmake_version(self.cmake_executable)
    File "/tmp/pip-build-env-45n19u0t/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
      raise SKBuildError(msg) from err

  Problem with the CMake installation, aborting build. CMake executable is /tmp/pip-build-env-45n19u0t/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /projects/academic/thapar/fpena/miniconda3/envs/textgen/bin/python /projects/academic/thapar/fpena/miniconda3/envs/textgen/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpd09vvcgp
  cwd: /tmp/pip-install-h2w8p32k/llama-cpp-python_5bdbf0a6f27c4e3cbfac658b135348d7
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

**Comment by abetlen** [comment]
@fpena06 thank you, can you try with the reinstall flags as well, this output doesn't really give anything to work off of.

**Comment by fpena06** [comment]
@abetlen this is with `pip install --verbose --upgrade --force-reinstall -r requirements.txt` version 0.1.48 installs fine.

```
Building wheels for collected packages: llama-cpp-python, peft
  Running command Building wheel for llama-cpp-python (pyproject.toml)
  Traceback (most recent call last):
    File "/tmp/pip-build-env-kekb8b9k/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "/tmp/pip-build-env-kekb8b9k/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 148, in __init__
      self.cmake_version = get_cmake_version(self.cmake_executable)
    File "/tmp/pip-build-env-kekb8b9k/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
      raise SKBuildError(msg) from err

  Problem with the CMake installation, aborting build. CMake executable is /tmp/pip-build-env-kekb8b9k/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /projects/academic/thapar/fpena/llm/text-generation-webui/venv/bin/python /projects/academic/thapar/fpena/llm/text-generation-webui/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpduxacufk
  cwd: /tmp/pip-install-94m2uix0/llama-cpp-python_6991439dbd094502a5590dc56f099623
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  ERROR: Failed building wheel for llama-cpp-python
  Running command git rev-parse HEAD
  e45529b149c7f91ec1d4d82a5a152ef56c56cb94
  Running command git show-ref e45529b149c7f91ec1d4d82a5a152ef56c56cb94
  Running command Building wheel for peft (pyproject.toml)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/peft
  copying src/peft/__init__.py -> build/lib/peft
  copying src/peft/mapping.py -> build/lib/peft
  copying src/peft/import_utils.py -> build/lib/peft
  copying src/peft/peft_model.py -> build/lib/peft
  creating build/lib/peft/tuners
  copying src/peft/tuners/lora.py -> build/lib/peft/tuners
  copying src/peft/tuners/__init__.py -> build/lib/peft/tuners
  copying src/peft/tuners/p_tuning.py -> build/lib/peft/tuners
  copying src/peft/tuners/prefix_tuning.py -> build/lib/peft/tuners
  copying src/peft/tuners/adaption_prompt.py -> build/lib/peft/tuners
  copying src/peft/tuners/prompt_tuning.py -> build/lib/peft/tuners
  copying src/peft/tuners/adalora.py -> build/lib/peft/tuners
  creating build/lib/peft/utils
  copying src/peft/utils/other.py -> build/lib/peft/utils
  copying src/peft/utils/__init__.py -> build/lib/peft/utils
  copying src/peft/utils/save_and_load.py -> build/lib/peft/utils
  copying src/peft/utils/config.py -> build/lib/peft/utils
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/peft
  copying build/lib/peft/__init__.py -> build/bdist.linux-x86_64/wheel/peft
  copying build/lib/peft/mapping.py -> build/bdist.linux-x86_64/wheel/peft
  creating build/bdist.linux-x86_64/wheel/peft/tuners
  copying build/lib/peft/tuners/lora.py -> build/bdist.linux-x86_64/wheel/peft/tuners
  copying build/lib/peft/tuners/__init__.py -> build/bdist.linux-x86_64/wheel/peft/tuners
  copying build/lib/peft/tuners/p_tuning.py -> build/bdist.linux-x86_64/wheel/peft/tuners
  copying build/lib/peft/tuners/prefix_tuning.py -> build/bdist.linux-x86_64/wheel/peft/tuners
  copying build/lib/peft/tuners/adaption_prompt.py -> build/bdist.linux-x86_64/wheel/peft/tuners
  copying build/lib/peft/tuners/prompt_tuning.py -> build/bdist.linux-x86_64/wheel/peft/tuners
  copying build/lib/peft/tuners/adalora.py -> build/bdist.linux-x86_64/wheel/peft/tuners
  copying build/lib/peft/import_utils.py -> build/bdist.linux-x86_64/wheel/peft
  copying build/lib/peft/peft_model.py -> build/bdist.linux-x86_64/wheel/peft
  creating build/bdist.linux-x86_64/wheel/peft/utils
  copying build/lib/peft/utils/other.py -> build/bdist.linux-x86_64/wheel/peft/utils
  copying build/lib/peft/utils/__init__.py -> build/bdist.linux-x86_64/wheel/peft/utils
  copying build/lib/peft/utils/save_and_load.py -> build/bdist.linux-x86_64/wheel/peft/utils
  copying build/lib/peft/utils/config.py -> build/bdist.linux-x86_64/wheel/peft/utils
  running install_egg_info
  running egg_info
  writing src/peft.egg-info/PKG-INFO
  writing dependency_links to src/peft.egg-info/dependency_links.txt
  writing requirements to src/peft.egg-info/requires.txt
  writing top-level names to src/peft.egg-info/top_level.txt
  reading manifest file 'src/peft.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'src/peft.egg-info/SOURCES.txt'
  Copying src/peft.egg-info to build/bdist.linux-x86_64/wheel/peft-0.4.0.dev0-py3.10.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/peft-0.4.0.dev0.dist-info/WHEEL
  creating '/tmp/pip-wheel-18viugi3/.tmp-jx4maczr/peft-0.4.0.dev0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'peft/__init__.py'
  adding 'peft/import_utils.py'
  adding 'peft/mapping.py'
  adding 'peft/peft_model.py'
  adding 'peft/tuners/__init__.py'
  adding 'peft/tuners/adalora.py'
  adding 'peft/tuners/adaption_prompt.py'
  adding 'peft/tuners/lora.py'
  adding 'peft/tuners/p_tuning.py'
  adding 'peft/tuners/prefix_tuning.py'
  adding 'peft/tuners/prompt_tuning.py'
  adding 'peft/utils/__init__.py'
  adding 'peft/utils/config.py'
  adding 'peft/utils/other.py'
  adding 'peft/utils/save_and_load.py'
  adding 'peft-0.4.0.dev0.dist-info/LICENSE'
  adding 'peft-0.4.0.dev0.dist-info/METADATA'
  adding 'peft-0.4.0.dev0.dist-info/WHEEL'
  adding 'peft-0.4.0.dev0.dist-info/top_level.txt'
  adding 'peft-0.4.0.dev0.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Building wheel for peft (pyproject.toml) ... done
  Created wheel for peft: filename=peft-0.4.0.dev0-py3-none-any.whl size=58226 sha256=e17c84f7a56b7e5f5d7eb488efccbd50f2cd690eeb73fd06bdeb7af1a96a5de6
  Stored in directory: /projects/academic/thapar/fpena/.cache/pip/wheels/75/5f/15/f22ec8074767da800560c87bf2e22117ba2bcacf96f442e920
Successfully built peft
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

**Comment by Aniruddha-Deb** [comment]
I think it's caused because of https://github.com/ggerganov/llama.cpp/issues/1788, maybe installing and building the latest version of that where `static_assert` are changed to `_Static_assert` will fix this

**Comment by fpena06** [comment]
> I think it's caused because of [ggerganov/llama.cpp#1788](https://github.com/ggerganov/llama.cpp/issues/1788), maybe installing and building the latest version of that where `static_assert`s are changed to `_Static_assert` will fix this

thanks, I was able to reproduce this issue with llama.cpp, which led to another issue which this [fixed](https://github.com/ggerganov/llama.cpp/issues/788#issuecomment-1498870115). But how can I make this changes in llama-cpp-python? I can't find k_quants.h or ggml.c, which I had to modify in llama.cpp. 

Thanks

**Comment by abetlen** [comment]
@fpena06 if you're building from source from the github repo, just follow the instructionns in the README and the llama.cpp project should be cloned to the vendor/llama.cpp subdirectory.

**Comment by fpena06** [comment]
> @fpena06 if you're building from source from the github repo, just follow the instructionns in the README and the llama.cpp project should be cloned to the vendor/llama.cpp subdirectory.

@abetlen worked like a charm after making the changes to llama.cpp and moving to vender folder and installing =)

```
(textgen) [fpena@vortex2:~/projects/llm/llama-cpp-python]$ pip install -e .
Obtaining file:///projects/academic/thapar/fpena/llm/llama-cpp-python
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in /projects/academic/thapar/fpena/miniconda3/envs/textgen/lib/python3.10/site-packages (from llama-cpp-python==0.1.63) (4.6.3)
Requirement already satisfied: numpy>=1.20.0 in /projects/academic/thapar/fpena/miniconda3/envs/textgen/lib/python3.10/site-packages (from llama-cpp-python==0.1.63) (1.25.0)
Collecting diskcache>=5.6.1 (from llama-cpp-python==0.1.63)
  Using cached diskcache-5.6.1-py3-none-any.whl (45 kB)
Building wheels for collected packages: llama-cpp-python
  Building editable for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.1.63-0.editable-py3-none-any.whl size=6297 sha256=8ce15a09b191ca46ccc9bb3ffe69f1a529cfde499a9039fa40b10090d6773b94
  Stored in directory: /tmp/pip-ephem-wheel-cache-ljbx53x5/wheels/e6/34/99/4838c156399d94c4764cf9f545ed38c46c029c3b0edea83b1c
Successfully built llama-cpp-python
Installing collected packages: diskcache, llama-cpp-python
  Attempting uninstall: llama-cpp-python
    Found existing installation: llama-cpp-python 0.1.48
    Uninstalling llama-cpp-python-0.1.48:
      Successfully uninstalled llama-cpp-python-0.1.48
Successfully installed diskcache-5.6.1 llama-cpp-python-0.1.63
```
