### ISSUE TITLE
OpenBLAS blas_thread_ init Error - Linux Centos 7 with llama-cpp-python == 0.1.67

### ISSUE THREAD

**Issue by omkargadute** [abetlen/llama-cpp-python#450]
I am trying to run the wizardvicuna ggml model using llama-cpp-python 0.1.67 inside a linux machine, but i am getting this following error, Earlier when i was using v0.1.55 it was working fine. I tried to look this issue on stackoverflow where people have suggested to increase the max user process limit, i did that using "ulimit -u unlimited", but was facing still the same problem, i tried serval other solution but still getting this issue. 

BASE OS - Centos 7 

# Failure Logs

Logs of the docker container - 
```
OpenBLAS blas_thread_ init: pthread_create failed for thread 1 of 12: Operation not permitted OpenBLAS blas_thread_init: RLIMIT_NPROC 1048576 current, 1048576 max

OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 12: Operation not permitted OpenBLAS blas_thread_init: LIMIT_ NPROC 1048576 current, 1048576 max

OpenBLAS blas_thread_init: pthread create failed for thread 3 of 12: Operation not permitted OpenBLAS blas_thread_init: LIMIT_NPROC 1048576 current, 1048576 max

OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 12: Operation not permitted OpenBLAS blas_ thread_init: RLIMIT_NPROC 1048576 current, 1048576 max

OpenBLAS blas_thread_init: pthread _create failed for thread 5 of 12: Operation not permitted OpenBLAS blas_thread_init: LIMIT_NPROC 1048576 current, 1048576 max

OpenBLAS blas_thread_init: thread _create failed for thread 6 of 12: Operation not permitted OpenBLAS blas_thread_init: LIMIT_NPROC 1048576 current, 1048576 max

OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 12: Operation not permitted OpenBLAS blas_thread_ init: LIMIT_NPROC 1048576 current, 1048576 max

OpenBLAS blas_thread_init: pthread_create failed for thread 8 of 12: Operation not permitted OpenBLAS blas_thread_ init: LIMIT_NPROC 1048576 current, 1048576 max

OpenBLAS blas thread init: thread create failed for thread 9 of 12: Operation not permitted OpenBLAS blas_thread_init: LIMIT_NPROC 1048576 current, 1048576 max

OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 12: Operation not permitted OpenBLAS blas_thread_init: LIMIT_NPROC 1048576 current, 1048576 max

OpenBLAS blas_ thread_init: thread _create failed for thread 11 of 12: Operation not permitted OpenBLAS blas_thread_init: RLIMIT_ NPROC 1048576 current, 1048576 max

Traceback (most recent call last):

File

*/usr/local/lib/python3.10/runpy-py", line 187, in _run_module_as main

mod _name, mod_spec, code = _get_module_details (mod _name, _Error)

File -/usr/local/lib/python3.10/rumpy.py", line 110, in Jet module_details

import__(pkg_name)

File */us/local/lib/python3.10/site-packages/llama_cpp/__init_py", line 2, in <modules from llama import *

File /usr/local/lib/python3.10/site-packages/11ama_cp/llama-py", line 26, in <module> import numpy as np

File "/usr/local/lib/python3.10/site-packages/numpy/__init_py", line 139, in <module> from import core

File "/us/local/lib/python3.10/site-packages/numpy/core/__init_

-•py", line 23, in ‹module>

from. import multiarray

File */us/local/lib/python3.10/site-packages/numpy/core/multiarray.py",line 10, in <module> from . import overrides

File */us/local/lib/python3.10/site-packages/numpy/core/overrides.py", line 8, in <modules from numpy.core._multiarray_umath import (

File "‹frozen importlib. _bootstrap›", line 216, in _lock_unlock module

KeyboardInterrupt

Model is available. Running the next command. ..python3 -m 11ama_cp.server --model $MODEL_PATH
```

**Comment by gjmulder** [comment]
Either Docker or OS inside the container is limiting the number of processes/threads you can fork.

Don't use CentOS images, as they are derived from RedHat and not something well supported in non-production environments.

[docker/openblas_simple](https://github.com/abetlen/llama-cpp-python/tree/main/docker/openblas_simple) uses a Debian distro that provides a minimal python3 image. It is both disk efficient and Docker friendly.

**Comment by DanielRolC** [comment]
I have the same issue with Ubuntu 22.04.
The main difference is that I have tested the same code (based on docker-compose) on several computers, and it works well on all of them except for the one that shows this error.

OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 12: opperation not permitted
OpenBLAS blas_thread_init: RLIMIT_INPROC -1 current, -1 max

This error pops up 12 times, 1 out of 12, 2 out of 12, 3 out of 12... always displaying the same message.

And finally, it gives me an import error from the cv2 library similar to the one at the beginning of the issue.

**Comment by saurabheights** [comment]
@DanielRolC Are you using docker version less than `1.27.9`. I was facing [this](https://stackoverflow.com/questions/70087344/python-in-docker-runtimeerror-cant-start-new-thread/70093119#70093119) error and in trying to fix it, ended up on the OpenBlas error.

**Comment by DanielRolC** [comment]
Finally, I upgraded the Docker version and the problem was solved!

**Comment by hemangjoshi37a** [comment]
@DanielRolC how did you update your docker ? Give me any command if possible.

**Comment by DanielRolC** [comment]
It's important to clarify that on my computer I have Ubuntu as the operating system

I don't remember exactly but you could try with this.

First, check the docker version:
- docker --version

Then:
- sudo apt update
- sudo apt upgrade

- sudo apt install docker-ce docker-ce-cli containerd.io

- sudo systemctl restart docker

Finally, check the docker update:
- docker --version

I hope this help you to solve this problem

**Comment by jbbqqf** [comment]
Hi @omkargadute — drive-by triage note, not a maintainer.

This thread already contains a confirmed resolution:

- @DanielRolC reported (2024-01-09) that upgrading Docker resolved the `OpenBLAS blas_thread_init: pthread_create failed` error.
- @saurabheights earlier linked the root cause to Docker < 1.27.9 (https://stackoverflow.com/questions/70087344), where the host kernel and Docker version disagree on thread/process limits.

The OP environment stack — CentOS 7, the legacy GGML model format (`.bin`), and llama-cpp-python 0.1.67 — is also all obsolete now: CentOS 7 is EOL, and llama.cpp moved to GGUF in Aug 2023 (the current library only loads GGUF model files).

So if you're still hitting this, the practical fix is one of:
1. Upgrade Docker to a current version (and ideally move off CentOS 7).
2. Re-test on a recent llama-cpp-python release (0.3.x) with a GGUF model.

Given the in-thread resolution + the stack being end-of-life, this looks safe to close.

---
*Disclosure: I'm Jean-Baptiste Braun (data engineer, GCP/Python). This comment was drafted with the help of an AI coding assistant (Claude), then reviewed and edited by me. Posting from a small open-source backlog-triage pass — not affiliated with the project. Happy to delete if unwelcome.*
