### ISSUE TITLE
Failed to load shared library due to broken C++ compile environment

### ISSUE THREAD

**Issue by spencerchubb** [abetlen/llama-cpp-python#468]
I looked at this [similar issue](https://github.com/abetlen/llama-cpp-python/issues/208), but the cause of the error is different for me.

OS: Amazon Linux

Version: Latest version of llama_cpp_python

Commands / code / output:
```
$ python
Python 3.9.16 (main, Feb 23 2023, 00:00:00)
[GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import llama_cpp
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/llama_cpp/llama_cpp.py", line 67, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), winmode=0)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ec2-user/.local/lib/python3.9/site-packages/llama_cpp/libllama.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.local/lib/python3.9/site-packages/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/home/ec2-user/.local/lib/python3.9/site-packages/llama_cpp/llama_cpp.py", line 80, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/llama_cpp/llama_cpp.py", line 69, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library '/home/ec2-user/.local/lib/python3.9/site-packages/llama_cpp/libllama.so': /home/ec2-user/.local/lib/python3.9/site-packages/llama_cpp/libllama.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE
```

**Comment by spencerchubb** [comment]
I figured out the issue rather quickly. I had an env variable called `CXX` set while installing the wheel, and I had to `unset CXX`

Maybe there is a way to fix this for others? I feel like the installation shouldn't break just because of having that env variable set 😊

**Comment by gjmulder** [comment]
Glad you fixed your compile environment. Can you close this issue?
