### ISSUE TITLE
model_path error with Llama-2

### ISSUE THREAD

**Issue by jadehardouin** [abetlen/llama-cpp-python#526]
I am trying to execute the following script:

1. from llama_cpp import Llama
2. llm = Llama(model_path="~/llama-2-7b.ggmlv3.q8_0.bin", n_gqa=8)
3. output = llm("Q: Name the planets in the solar system? A: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
4. print(output)

where the model is Llama-2-7b in GGML format (found here : https://huggingface.co/TheBloke/Llama-2-7B-GGML) that I downloaded on my local machine in the directory home/jade

But I get this error: 
Traceback (most recent call last):
  File "/home/jadeh/llama_inference.py", line 9, in <module>
    llm = Llama(model_path="home/jadeh/llama-2-7b.ggmlv3.q8_0.bin", n_gqa=8)
  File "/home/jadeh/myenv/lib/python3.10/site-packages/llama_cpp/llama.py", line 308, in __init__
    raise ValueError(f"Model path does not exist: {model_path}")
ValueError: Model path does not exist: ~/llama-2-7b.ggmlv3.q8_0.bin

Previously, I tried using the model files provided by Meta but got the same error about the model_path. Can you explain to me how to correctly use this "model_path" argument please?

**Comment by AmineDjeghri** [comment]
i'm using the model path and it works correctly 
try this to f find here is the problem first :
- create a folder names as your model name which contains the bin & json file of your model
and try again

**Comment by zhiyuanyou** [comment]
Hello, I winder 

> I am trying to execute the following script:
> 
> 1. from llama_cpp import Llama
> 2. llm = Llama(model_path="~/llama-2-7b.ggmlv3.q8_0.bin", n_gqa=8)
> 3. output = llm("Q: Name the planets in the solar system? A: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
> 4. print(output)
> 
> where the model is Llama-2-7b in GGML format (found here : https://huggingface.co/TheBloke/Llama-2-7B-GGML) that I downloaded on my local machine in the directory home/jade
> 
> But I get this error: Traceback (most recent call last): File "/home/jadeh/llama_inference.py", line 9, in llm = Llama(model_path="home/jadeh/llama-2-7b.ggmlv3.q8_0.bin", n_gqa=8) File "/home/jadeh/myenv/lib/python3.10/site-packages/llama_cpp/llama.py", line 308, in **init** raise ValueError(f"Model path does not exist: {model_path}") ValueError: Model path does not exist: ~/llama-2-7b.ggmlv3.q8_0.bin
> 
> Previously, I tried using the model files provided by Meta but got the same error about the model_path. Can you explain to me how to correctly use this "model_path" argument please?

Hello, I wonder whether the GGML format model (https://huggingface.co/TheBloke/Llama-2-7B-GGML) is the chat-style model finetuned with RLHF?

**Comment by varunsalunkhe** [comment]
Im getting the sam error.
