### ISSUE TITLE
llama-cpp-python server docker container fails to start

### ISSUE THREAD

**Issue by dimaguy** [abetlen/llama-cpp-python#535]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

The container is supposed to start normally

# Current Behavior

It exits with code 1 with error ``"llama" object has no attribute 'model'``

# Environment and Context

Running on a freshly pulled image with the following docker compose file:
```
version: '3.3'
services:
    llamacpp:
        ports:
            - '8000:8000'
        volumes:
            - './models:/models'
        environment:
            - MODEL=models/luna-ai-llama2-uncensored.ggmlv3.q2_K.bin
        image: 'ghcr.io/abetlen/llama-cpp-python:latest'
```
lscpu output:
```
Architecture:           x86_64
  CPU op-mode(s):       32-bit, 64-bit
  Address sizes:        39 bits physical, 48 bits virtual
  Byte Order:           Little Endian
CPU(s):                 8
  On-line CPU(s) list:  0-7
Vendor ID:              GenuineIntel
  Model name:           Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    CPU family:         6
    Model:              158
    Thread(s) per core: 2
    Core(s) per socket: 4
    Socket(s):          1
    Stepping:           9
    CPU(s) scaling MHz: 57%
    CPU max MHz:        3800,0000
    CPU min MHz:        800,0000
    BogoMIPS:           5599,85
    Flags:              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl x                        topology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm                         abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dthe                        rm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
Caches (sum of all):    
  L1d:                  128 KiB (4 instances)
  L1i:                  128 KiB (4 instances)
  L2:                   1 MiB (4 instances)
  L3:                   6 MiB (1 instance)
NUMA:                   
  NUMA node(s):         1
  NUMA node0 CPU(s):    0-7
Vulnerabilities:        
  Itlb multihit:        KVM: Mitigation: VMX unsupported
  L1tf:                 Mitigation; PTE Inversion
  Mds:                  Mitigation; Clear CPU buffers; SMT vulnerable
  Meltdown:             Mitigation; PTI
  Mmio stale data:      Mitigation; Clear CPU buffers; SMT vulnerable
  Retbleed:             Mitigation; IBRS
  Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:           Mitigation; IBRS, IBPB conditional, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                Mitigation; Microcode
  Tsx async abort:      Not affected
```
# Failure Information (for bugs)

# Steps to Reproduce

1. docker compose up
2. error ensues

# Failure Logs
```
[+] Running 1/1
 ✔ Container llama-cpp-python-llamacpp-1  Created                                                                                                                                                                            17.5s 
Attaching to llama-cpp-python-llamacpp-1
llama-cpp-python-llamacpp-1  | python3 setup.py develop
llama-cpp-python-llamacpp-1  | /usr/local/lib/python3.11/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
llama-cpp-python-llamacpp-1  | !!
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  |         ********************************************************************************
llama-cpp-python-llamacpp-1  |         Please avoid running ``setup.py`` and ``easy_install``.
llama-cpp-python-llamacpp-1  |         Instead, use pypa/build, pypa/installer or other
llama-cpp-python-llamacpp-1  |         standards-based tools.
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  |         See https://github.com/pypa/setuptools/issues/917 for details.
llama-cpp-python-llamacpp-1  |         ********************************************************************************
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | !!
llama-cpp-python-llamacpp-1  |   easy_install.initialize_options(self)
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | --------------------------------------------------------------------------------
llama-cpp-python-llamacpp-1  | -- Trying 'Ninja' generator
llama-cpp-python-llamacpp-1  | --------------------------------
llama-cpp-python-llamacpp-1  | ---------------------------
llama-cpp-python-llamacpp-1  | ----------------------
llama-cpp-python-llamacpp-1  | -----------------
llama-cpp-python-llamacpp-1  | ------------
llama-cpp-python-llamacpp-1  | -------
llama-cpp-python-llamacpp-1  | --
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | Not searching for unused variables given on the command line.
llama-cpp-python-llamacpp-1  | CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
llama-cpp-python-llamacpp-1  |   Compatibility with CMake < 3.5 will be removed from a future version of
llama-cpp-python-llamacpp-1  |   CMake.
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  |   Update the VERSION argument <min> value or use a ...<max> suffix to tell
llama-cpp-python-llamacpp-1  |   CMake that the project does not need compatibility with older versions.
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | -- The C compiler identification is GNU 10.2.1
llama-cpp-python-llamacpp-1  | -- Detecting C compiler ABI info
llama-cpp-python-llamacpp-1  | -- Detecting C compiler ABI info - done
llama-cpp-python-llamacpp-1  | -- Check for working C compiler: /usr/bin/cc - skipped
llama-cpp-python-llamacpp-1  | -- Detecting C compile features
llama-cpp-python-llamacpp-1  | -- Detecting C compile features - done
llama-cpp-python-llamacpp-1  | -- The CXX compiler identification is GNU 10.2.1
llama-cpp-python-llamacpp-1  | -- Detecting CXX compiler ABI info
llama-cpp-python-llamacpp-1  | -- Detecting CXX compiler ABI info - done
llama-cpp-python-llamacpp-1  | -- Check for working CXX compiler: /usr/bin/c++ - skipped
llama-cpp-python-llamacpp-1  | -- Detecting CXX compile features
llama-cpp-python-llamacpp-1  | -- Detecting CXX compile features - done
llama-cpp-python-llamacpp-1  | -- Configuring done (0.3s)
llama-cpp-python-llamacpp-1  | -- Generating done (0.0s)
llama-cpp-python-llamacpp-1  | -- Build files have been written to: /app/_cmake_test_compile/build
llama-cpp-python-llamacpp-1  | --
llama-cpp-python-llamacpp-1  | -------
llama-cpp-python-llamacpp-1  | ------------
llama-cpp-python-llamacpp-1  | -----------------
llama-cpp-python-llamacpp-1  | ----------------------
llama-cpp-python-llamacpp-1  | ---------------------------
llama-cpp-python-llamacpp-1  | --------------------------------
llama-cpp-python-llamacpp-1  | -- Trying 'Ninja' generator - success
llama-cpp-python-llamacpp-1  | --------------------------------------------------------------------------------
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | Configuring Project
llama-cpp-python-llamacpp-1  |   Working directory:
llama-cpp-python-llamacpp-1  |     /app/_skbuild/linux-x86_64-3.11/cmake-build
llama-cpp-python-llamacpp-1  |   Command:
llama-cpp-python-llamacpp-1  |     /usr/local/lib/python3.11/site-packages/cmake/data/bin/cmake /app -G Ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/app/_skbuild/linux-x86_64-3.11/cmake-install -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/usr/local/lib/python3.11/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/local/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/local/include/python3.11 -DPYTHON_LIBRARY:PATH=/usr/local/lib/libpython3.11.so -DPython_EXECUTABLE:PATH=/usr/local/bin/python3 -DPython_ROOT_DIR:PATH=/usr/local -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/local/include/python3.11 -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/local/lib/python3.11/site-packages/numpy-1.25.1-py3.11-linux-x86_64.egg/numpy/core/include -DPython3_EXECUTABLE:PATH=/usr/local/bin/python3 -DPython3_ROOT_DIR:PATH=/usr/local -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/local/include/python3.11 -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/local/lib/python3.11/site-packages/numpy-1.25.1-py3.11-linux-x86_64.egg/numpy/core/include -DCMAKE_BUILD_TYPE:STRING=Release
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | Not searching for unused variables given on the command line.
llama-cpp-python-llamacpp-1  | -- The C compiler identification is GNU 10.2.1
llama-cpp-python-llamacpp-1  | -- The CXX compiler identification is GNU 10.2.1
llama-cpp-python-llamacpp-1  | -- Detecting C compiler ABI info
llama-cpp-python-llamacpp-1  | -- Detecting C compiler ABI info - done
llama-cpp-python-llamacpp-1  | -- Check for working C compiler: /usr/bin/cc - skipped
llama-cpp-python-llamacpp-1  | -- Detecting C compile features
llama-cpp-python-llamacpp-1  | -- Detecting C compile features - done
llama-cpp-python-llamacpp-1  | -- Detecting CXX compiler ABI info
llama-cpp-python-llamacpp-1  | -- Detecting CXX compiler ABI info - done
llama-cpp-python-llamacpp-1  | -- Check for working CXX compiler: /usr/bin/c++ - skipped
llama-cpp-python-llamacpp-1  | -- Detecting CXX compile features
llama-cpp-python-llamacpp-1  | -- Detecting CXX compile features - done
llama-cpp-python-llamacpp-1  | -- Configuring done (0.3s)
llama-cpp-python-llamacpp-1  | -- Generating done (0.0s)
llama-cpp-python-llamacpp-1  | -- Build files have been written to: /app/_skbuild/linux-x86_64-3.11/cmake-build
llama-cpp-python-llamacpp-1  | [1/2] Generating /app/vendor/llama.cpp/libllama.so
llama-cpp-python-llamacpp-1  | make[1]: Entering directory '/app/vendor/llama.cpp'
llama-cpp-python-llamacpp-1  | I llama.cpp build info: 
llama-cpp-python-llamacpp-1  | I UNAME_S:  Linux
llama-cpp-python-llamacpp-1  | I UNAME_P:  unknown
llama-cpp-python-llamacpp-1  | I UNAME_M:  x86_64
llama-cpp-python-llamacpp-1  | I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS
llama-cpp-python-llamacpp-1  | I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS
llama-cpp-python-llamacpp-1  | I LDFLAGS:  
llama-cpp-python-llamacpp-1  | I CC:       cc (Debian 10.2.1-6) 10.2.1 20210110
llama-cpp-python-llamacpp-1  | I CXX:      g++ (Debian 10.2.1-6) 10.2.1 20210110
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -c llama.cpp -o llama.o
llama-cpp-python-llamacpp-1  | cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS   -c ggml.c -o ggml.o
llama-cpp-python-llamacpp-1  | cc -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS   -c -o k_quants.o k_quants.c
llama-cpp-python-llamacpp-1  | g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -shared -fPIC -o libllama.so llama.o ggml.o k_quants.o 
llama-cpp-python-llamacpp-1  | make[1]: Leaving directory '/app/vendor/llama.cpp'
llama-cpp-python-llamacpp-1  | [1/2] Install the project...
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | -- Install configuration: "Release"
llama-cpp-python-llamacpp-1  | -- Installing: /app/_skbuild/linux-x86_64-3.11/cmake-install/llama_cpp/libllama.so
llama-cpp-python-llamacpp-1  | copying _skbuild/linux-x86_64-3.11/cmake-install/llama_cpp/libllama.so -> llama_cpp/libllama.so
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | running develop
llama-cpp-python-llamacpp-1  | /usr/local/lib/python3.11/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
llama-cpp-python-llamacpp-1  | !!
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  |         ********************************************************************************
llama-cpp-python-llamacpp-1  |         Please avoid running ``setup.py`` and ``easy_install``.
llama-cpp-python-llamacpp-1  |         Instead, use pypa/build, pypa/installer or other
llama-cpp-python-llamacpp-1  |         standards-based tools.
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  |         See https://github.com/pypa/setuptools/issues/917 for details.
llama-cpp-python-llamacpp-1  |         ********************************************************************************
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | !!
llama-cpp-python-llamacpp-1  |   easy_install.initialize_options(self)
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | /usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
llama-cpp-python-llamacpp-1  | !!
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  |         ********************************************************************************
llama-cpp-python-llamacpp-1  |         Please avoid running ``setup.py`` directly.
llama-cpp-python-llamacpp-1  |         Instead, use pypa/build, pypa/installer or other
llama-cpp-python-llamacpp-1  |         standards-based tools.
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  |         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
llama-cpp-python-llamacpp-1  |         ********************************************************************************
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | !!
llama-cpp-python-llamacpp-1  |   self.initialize_options()
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | running egg_info
llama-cpp-python-llamacpp-1  | writing llama_cpp_python.egg-info/PKG-INFO
llama-cpp-python-llamacpp-1  | writing dependency_links to llama_cpp_python.egg-info/dependency_links.txt
llama-cpp-python-llamacpp-1  | writing requirements to llama_cpp_python.egg-info/requires.txt
llama-cpp-python-llamacpp-1  | writing top-level names to llama_cpp_python.egg-info/top_level.txt
llama-cpp-python-llamacpp-1  | reading manifest file 'llama_cpp_python.egg-info/SOURCES.txt'
llama-cpp-python-llamacpp-1  | adding license file 'LICENSE.md'
llama-cpp-python-llamacpp-1  | writing manifest file 'llama_cpp_python.egg-info/SOURCES.txt'
llama-cpp-python-llamacpp-1  | running build_ext
llama-cpp-python-llamacpp-1  | Creating /usr/local/lib/python3.11/site-packages/llama-cpp-python.egg-link (link to .)
llama-cpp-python-llamacpp-1  | llama-cpp-python 0.1.77 is already the active version in easy-install.pth
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | Installed /app
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | Processing dependencies for llama-cpp-python==0.1.77
llama-cpp-python-llamacpp-1  | Searching for diskcache==5.6.1
llama-cpp-python-llamacpp-1  | Best match: diskcache 5.6.1
llama-cpp-python-llamacpp-1  | Processing diskcache-5.6.1-py3.11.egg
llama-cpp-python-llamacpp-1  | Adding diskcache 5.6.1 to easy-install.pth file
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | Using /usr/local/lib/python3.11/site-packages/diskcache-5.6.1-py3.11.egg
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | Searching for numpy==1.25.1
llama-cpp-python-llamacpp-1  | Best match: numpy 1.25.1
llama-cpp-python-llamacpp-1  | Processing numpy-1.25.1-py3.11-linux-x86_64.egg
llama-cpp-python-llamacpp-1  | Adding numpy 1.25.1 to easy-install.pth file
llama-cpp-python-llamacpp-1  | Installing f2py script to /usr/local/bin
llama-cpp-python-llamacpp-1  | Installing f2py3 script to /usr/local/bin
llama-cpp-python-llamacpp-1  | Installing f2py3.11 script to /usr/local/bin
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | Using /usr/local/lib/python3.11/site-packages/numpy-1.25.1-py3.11-linux-x86_64.egg
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | Searching for typing-extensions==4.7.1
llama-cpp-python-llamacpp-1  | Best match: typing-extensions 4.7.1
llama-cpp-python-llamacpp-1  | Adding typing-extensions 4.7.1 to easy-install.pth file
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | Using /usr/local/lib/python3.11/site-packages
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | Finished processing dependencies for llama-cpp-python==0.1.77
llama-cpp-python-llamacpp-1  | /usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:126: UserWarning: Field "model_alias" has conflict with protected namespace "model_".
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ('settings_',)`.
llama-cpp-python-llamacpp-1  |   warnings.warn(
llama-cpp-python-llamacpp-1  | 
llama-cpp-python-llamacpp-1  | Traceback (most recent call last):
llama-cpp-python-llamacpp-1  |   File "/usr/local/bin/uvicorn", line 8, in <module>
llama-cpp-python-llamacpp-1  |     sys.exit(main())
llama-cpp-python-llamacpp-1  |              ^^^^^^
llama-cpp-python-llamacpp-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
llama-cpp-python-llamacpp-1  |     return self.main(*args, **kwargs)
llama-cpp-python-llamacpp-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
llama-cpp-python-llamacpp-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
llama-cpp-python-llamacpp-1  |     rv = self.invoke(ctx)
llama-cpp-python-llamacpp-1  |          ^^^^^^^^^^^^^^^^
llama-cpp-python-llamacpp-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
llama-cpp-python-llamacpp-1  |     return ctx.invoke(self.callback, **ctx.params)
llama-cpp-python-llamacpp-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llama-cpp-python-llamacpp-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
llama-cpp-python-llamacpp-1  |     return __callback(*args, **kwargs)
llama-cpp-python-llamacpp-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
llama-cpp-python-llamacpp-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
llama-cpp-python-llamacpp-1  |     run(
llama-cpp-python-llamacpp-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
llama-cpp-python-llamacpp-1  |     server.run()
llama-cpp-python-llamacpp-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
llama-cpp-python-llamacpp-1  |     return asyncio.run(self.serve(sockets=sockets))
llama-cpp-python-llamacpp-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llama-cpp-python-llamacpp-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
llama-cpp-python-llamacpp-1  |     return runner.run(main)
llama-cpp-python-llamacpp-1  |            ^^^^^^^^^^^^^^^^
llama-cpp-python-llamacpp-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
llama-cpp-python-llamacpp-1  |     return self._loop.run_until_complete(task)
llama-cpp-python-llamacpp-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llama-cpp-python-llamacpp-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
llama-cpp-python-llamacpp-1  |     return future.result()
llama-cpp-python-llamacpp-1  |            ^^^^^^^^^^^^^^^
llama-cpp-python-llamacpp-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
llama-cpp-python-llamacpp-1  |     config.load()
llama-cpp-python-llamacpp-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
llama-cpp-python-llamacpp-1  |     self.loaded_app = self.loaded_app()
llama-cpp-python-llamacpp-1  |                       ^^^^^^^^^^^^^^^^^
llama-cpp-python-llamacpp-1  |   File "/app/llama_cpp/server/app.py", line 313, in create_app
llama-cpp-python-llamacpp-1  |     llama = llama_cpp.Llama(
llama-cpp-python-llamacpp-1  |             ^^^^^^^^^^^^^^^^
llama-cpp-python-llamacpp-1  |   File "/app/llama_cpp/llama.py", line 308, in __init__
llama-cpp-python-llamacpp-1  |     raise ValueError(f"Model path does not exist: {model_path}")
llama-cpp-python-llamacpp-1  | ValueError: Model path does not exist: models/luna-ai-llama2-uncensored.ggmlv3.q2_K.bin
llama-cpp-python-llamacpp-1  | Exception ignored in: <function Llama.__del__ at 0x7f5d29f1cb80>
llama-cpp-python-llamacpp-1  | Traceback (most recent call last):
llama-cpp-python-llamacpp-1  |   File "/app/llama_cpp/llama.py", line 1507, in __del__
llama-cpp-python-llamacpp-1  | AttributeError: 'Llama' object has no attribute 'model'
llama-cpp-python-llamacpp-1 exited with code 1
```

**Comment by abetlen** [comment]
@dimaguy does changing the compose file to:

```
version: '3.3'
services:
    llamacpp:
        ports:
            - '8000:8000'
        volumes:
            - './models:/models'
        environment:
            - MODEL=/models/luna-ai-llama2-uncensored.ggmlv3.q2_K.bin
        image: 'ghcr.io/abetlen/llama-cpp-python:latest'
```

work? I think the model path was just set relative to the start directory which is `/app`

**Comment by dimaguy** [comment]
Yep! It works now, thanks! A couple of suggestions that could help avoid this in the future would be to change /models to /app/models in the volumes, or to create a link between /app/models and /models to make it foolproof
