### ISSUE TITLE
Failure to install in a sagemaker ml.g4dn notebook instance

### ISSUE THREAD

**Issue by ElisaSuarez** [abetlen/llama-cpp-python#552]
Hi all, I was trying to install llama-cpp-python on a sagemaker notebook instance running the conda_pytorch_p310 environment. The notebook is using a ml.g4dn instance and I have succesfully tried the llama test code in the machine. The problem comes when installing the llama-cpp-python.

I've tried installing with the following lines:
`pip install llama-cpp-python`
`!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python`
`!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir`

And I get the following output
```
Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com/
Collecting llama-cpp-python
  Downloading llama_cpp_python-0.1.77.tar.gz (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 123.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in /home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages (from llama-cpp-python) (4.5.0)
Requirement already satisfied: numpy>=1.20.0 in /home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages (from llama-cpp-python) (1.21.6)
Collecting diskcache>=5.6.1 (from llama-cpp-python)
  Downloading diskcache-5.6.1-py3-none-any.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 176.4 MB/s eta 0:00:00
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [107 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      Not searching for unused variables given on the command line.
      
      -- The C compiler identification is GNU 7.3.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 7.3.1
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.4s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-w7na_1ph/llama-cpp-python_ad0736a360334b409c13ec1ca9bfe25c/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /tmp/pip-install-w7na_1ph/llama-cpp-python_ad0736a360334b409c13ec1ca9bfe25c/_skbuild/linux-x86_64-3.7/cmake-build
        Command:
          /tmp/pip-build-env-wl9sa2zy/overlay/lib/python3.7/site-packages/cmake/data/bin/cmake /tmp/pip-install-w7na_1ph/llama-cpp-python_ad0736a360334b409c13ec1ca9bfe25c -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-wl9sa2zy/overlay/lib/python3.7/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-w7na_1ph/llama-cpp-python_ad0736a360334b409c13ec1ca9bfe25c/_skbuild/linux-x86_64-3.7/cmake-install -DPYTHON_VERSION_STRING:STRING=3.7.10 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-wl9sa2zy/overlay/lib/python3.7/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/bin/python3.7 -DPYTHON_INCLUDE_DIR:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/include/python3.7m -DPYTHON_LIBRARY:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/libpython3.7m.so -DPython_EXECUTABLE:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/bin/python3.7 -DPython_ROOT_DIR:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/include/python3.7m -DPython3_EXECUTABLE:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/bin/python3.7 -DPython3_ROOT_DIR:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/include/python3.7m -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-wl9sa2zy/overlay/lib/python3.7/site-packages/ninja/data/bin/ninja -DLLAMA_CUBLAS=on -DCMAKE_BUILD_TYPE:STRING=Release -DLLAMA_CUBLAS=on
      
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 7.3.1
      -- The CXX compiler identification is GNU 7.3.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Git: /usr/bin/git (found version "2.40.1")
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      CMake Warning at vendor/llama.cpp/CMakeLists.txt:116 (message):
        Git repository not found; to enable automatic generation of build info,
        make sure Git is installed and the project is a Git repository.
      
      
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Check if compiler accepts -pthread
      -- Check if compiler accepts -pthread - yes
      -- Found Threads: TRUE
      -- Found CUDAToolkit: /usr/local/cuda/include (found version "11.0.221")
      -- cuBLAS found
      -- The CUDA compiler identification is unknown
      CMake Error at /tmp/pip-build-env-wl9sa2zy/overlay/lib/python3.7/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCUDACompiler.cmake:603 (message):
        Failed to detect a default CUDA architecture.
      
      
      
        Compiler output:
      
      Call Stack (most recent call first):
        vendor/llama.cpp/CMakeLists.txt:249 (enable_language)
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-build-env-wl9sa2zy/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 671, in setup
          languages=cmake_languages,
        File "/tmp/pip-build-env-wl9sa2zy/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 357, in configure
          raise SKBuildError(msg)
      
      An error occurred while configuring with CMake.
        Command:
          /tmp/pip-build-env-wl9sa2zy/overlay/lib/python3.7/site-packages/cmake/data/bin/cmake /tmp/pip-install-w7na_1ph/llama-cpp-python_ad0736a360334b409c13ec1ca9bfe25c -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-wl9sa2zy/overlay/lib/python3.7/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-w7na_1ph/llama-cpp-python_ad0736a360334b409c13ec1ca9bfe25c/_skbuild/linux-x86_64-3.7/cmake-install -DPYTHON_VERSION_STRING:STRING=3.7.10 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-wl9sa2zy/overlay/lib/python3.7/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/bin/python3.7 -DPYTHON_INCLUDE_DIR:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/include/python3.7m -DPYTHON_LIBRARY:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/libpython3.7m.so -DPython_EXECUTABLE:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/bin/python3.7 -DPython_ROOT_DIR:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/include/python3.7m -DPython3_EXECUTABLE:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/bin/python3.7 -DPython3_ROOT_DIR:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/include/python3.7m -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-wl9sa2zy/overlay/lib/python3.7/site-packages/ninja/data/bin/ninja -DLLAMA_CUBLAS=on -DCMAKE_BUILD_TYPE:STRING=Release -DLLAMA_CUBLAS=on
        Source directory:
          /tmp/pip-install-w7na_1ph/llama-cpp-python_ad0736a360334b409c13ec1ca9bfe25c
        Working directory:
          /tmp/pip-install-w7na_1ph/llama-cpp-python_ad0736a360334b409c13ec1ca9bfe25c/_skbuild/linux-x86_64-3.7/cmake-build
      Please see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

Environment Info:
```
$uname -a
Linux ip-172-16-92-205.us-east-2.compute.internal 5.10.178-162.673.amzn2.x86_64 #1 SMP Mon Apr 24 23:34:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$!python --version
Python 3.10.10

$!make --version
GNU Make 3.82
Built for x86_64-koji-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$!g++ --version
g++ (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by richardr1126** [comment]
Same thing for me

**Comment by anshsarkar** [comment]
@ElisaSuarez @richardr1126 
I am facing the same issue. Were you guys able to solve this? Any help would be appreciated
