### ISSUE TITLE
Pip install failure on SuSE Linux

### ISSUE THREAD

**Issue by Teeeeg** [abetlen/llama-cpp-python#605]
I can not install this on my SUSE server.
Please help.

```
Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-2zursaa7/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/tmp/pip-build-env-2zursaa7/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 148, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/tmp/pip-build-env-2zursaa7/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
          raise SKBuildError(msg) from err
     
      Problem with the CMake installation, aborting build. CMake executable is /tmp/pip-build-env-2zursaa7/overlay/lib/python3.8/site-packages/cmake/data/bin/cmake
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

**Comment by limcheekin** [comment]
I had the same issue when using the following config:
```
CMAKE_ARGS="-DLLAMA_BLAS=ON -DLLAMA_BLAS_VENDOR=OpenBLAS" FORCE_CMAKE=1 pip install llama-cpp-python[server]
```

But it works after change back to the old config:
```
CMAKE_ARGS="-DLLAMA_OPENBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python[server]
```

Not sure the different though. I hope someone here could elaborate more.

**Comment by gjmulder** [comment]
Those are `CMake` flags passed to the `llama.cpp` build.

As per the issue template, try building llama.cpp and see if you can reproduce the same issue. If so, not a `llama-cpp-python` bug.

**Comment by gjmulder** [comment]
> raise SKBuildError(msg) from err

The issue template requests you to confirm your gcc version, OS version, python version, etc. In many cases SuSE is missing a `gcc` compiler.

Try adding the `--verbose` option to the `pip install` and it might show you the actual error.

**Comment by limcheekin** [comment]
@gjmulder Thanks for reminder of adding `--verbose` for troubleshooting.

I found the following error:
```
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
```

And it is fix by simply install the package with the following command:
```
sudo apt-get install pkg-config
```

Hope this help.

**Comment by Teeeeg** [comment]
I am sorry, I lost access to my account last month. I think this problem still has in my system.
```
Building wheels for collected packages: llama-cpp-python
  Running command Building wheel for llama-cpp-python (pyproject.toml)
  Traceback (most recent call last):
    File "/tmp/pip-build-env-mnys_6we/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "/tmp/pip-build-env-mnys_6we/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 148, in __init__
      self.cmake_version = get_cmake_version(self.cmake_executable)
    File "/tmp/pip-build-env-mnys_6we/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
      raise SKBuildError(msg) from err

  Problem with the CMake installation, aborting build. CMake executable is /tmp/pip-build-env-mnys_6we/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/dev3/miniconda3/envs/textgen/bin/python /home/dev3/miniconda3/envs/textgen/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmp34vi7f7y
  cwd: /tmp/pip-install-r0i_0bnc/llama-cpp-python_7c3a64ef13504d9f8aa2e0dc560dc819
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```
gcc version: gcc version 7.5.0 (SUSE Linux)
python: 3.10
OS: VERSION="15-SP4"
