### ISSUE TITLE
AttributeError: 'TensorNameMap' object has no attribute 'get'

### ISSUE THREAD

**Issue by earonesty** [abetlen/llama-cpp-python#654]
# Expected Behavior

`convert-llama-ggmlv3-to-gguf.py --input wizardlm-llama2-13b.ggmlv3.q4_K_S.bin --output wizard.gguf`

should result in a gguf file... 

# Current Behavior

```
* Preparing to save GGUF file
* Adding model parameters and KV items
* Adding 32000 vocab item(s)
* Adding 146 tensor(s)
Traceback (most recent call last):
  File "C:\Users\erik\llama.cpp\convert-llama-ggmlv3-to-gguf.py", line 345, in <module>
    main()
  File "C:\Users\erik\llama.cpp\convert-llama-ggmlv3-to-gguf.py", line 341, in main
    converter.save()
  File "C:\Users\erik\llama.cpp\convert-llama-ggmlv3-to-gguf.py", line 165, in save
    self.add_tensors(gguf_writer)
  File "C:\Users\erik\llama.cpp\convert-llama-ggmlv3-to-gguf.py", line 273, in add_tensors
    mapped_name = nm.get(name)
                  ^^^^^^
AttributeError: 'TensorNameMap' object has no attribute 'get'
```

Some context, the tensor name is "tok_embeddings"

# Environment and Context

MINGW64_NT-10.0-19045 LAPTOP-1K8B9NQ8 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

 1. download a ggml model file
 2. pip install gguf numpy
 3. convert-llama-ggmlv3-to-gguf.py --input wizardlm-llama2-13b.ggmlv3.q4_K_S.bin --output wizard.gguf

**Comment by earonesty** [comment]
Problem solved.   "gguf" at pypi is not compatible.

Using `pip install gguf-py/` works to fix.  

Probably the convert-llama-ggmlv3-to-gguf.py should know about that (if import fails, or if version mismatches, spit out an error)

**Comment by earonesty** [comment]
ok, after getting that to work there is a new error:
```
error loading model: create_tensor: tensor 'blk.15.ffn_norm.weight' not found
```

**Comment by earonesty** [comment]
ok, fixed that too, i had downloaded a partial file, and for whatever reason, there were zero errors.
