### ISSUE TITLE
how to download the model? 

### ISSUE THREAD

**Issue by futianfan** [abetlen/llama-cpp-python#664]

**Comment by reddiamond1234** [comment]
Find & download model in TheBloke's model repo (https://huggingface.co/TheBloke). I suggest downloading GGML version. Then convert it using code provided in this Llama.cpp repo - find python script "convert-llama-ggmlv3-to-gguf.py" (https://github.com/ggerganov/llama.cpp/tree/gguf), and then you're ready to go

**Comment by brrbaral** [comment]
``Hi @reddiamond1234, 
Can we create a full example of getting started from scratch? 
I have tried as well but cannot load a model. 
Here is my code, Please review and help to get started. 

```
!pip install llama-cpp-python
#download models 
!wget 'https://huggingface.co/TheBloke/llama2-7b-chat-codeCherryPop-qLoRA-GGML'

# Convert Model
!python /content/llama.cpp/convert-llama-ggmlv3-to-gguf.py \
 --input '/content/llama2-7b-chat-codeCherryPop-qLoRA-GGML' \
 --output llama2-7b-chat-codeCherryPop-qLoRA-GGML_converted
```

Executing this I got error as : 
```
* Using config: Namespace(input=PosixPath('/content/llama2-7b-chat-codeCherryPop-qLoRA-GGML'), output=PosixPath('llama2-7b-chat-codeCherryPop-qLoRA-GGML_converted'), name=None, desc=None, gqa=1, eps='5.0e-06', context_length=2048, model_metadata_dir=None, vocab_dir=None, vocabtype='spm')

=== WARNING === Be aware that this conversion script is best-effort. Use a native GGUF model if possible. === WARNING ===

* Scanning GGML input file
Traceback (most recent call last):
  File "/content/llama.cpp/convert-llama-ggmlv3-to-gguf.py", line 353, in <module>
    main()
  File "/content/llama.cpp/convert-llama-ggmlv3-to-gguf.py", line 335, in main
    offset = model.load(data, 0)
  File "/content/llama.cpp/convert-llama-ggmlv3-to-gguf.py", line 125, in load
    offset += self.validate_header(data, offset)
  File "/content/llama.cpp/convert-llama-ggmlv3-to-gguf.py", line 121, in validate_header
    raise ValueError('Only GGJTv3 supported')
ValueError: Only GGJTv3 supported

```
And I tried API using model files, but got error again as : 
```
model_path='/content/llama.cpp/models/ggml-vocab-llama.gguf'
from llama_cpp import Llama
llm = Llama(model_path=model_path)
output = llm("Q: Name the planets in the solar system? A: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
print(output)
```
Error: 
```
AssertionError                            Traceback (most recent call last)
[<ipython-input-14-b8c5f4eb5cc9>](https://localhost:8080/#) in <cell line: 4>()
      2 model_path='/content/llama.cpp/models/ggml-vocab-llama.gguf'
      3 from llama_cpp import Llama
----> 4 llm = Llama(model_path=model_path)
      5 output = llm("Q: Name the planets in the solar system? A: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
      6 print(output)

[/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py](https://localhost:8080/#) in __init__(self, model_path, n_ctx, n_parts, n_gpu_layers, seed, f16_kv, logits_all, vocab_only, use_mmap, use_mlock, embedding, n_threads, n_batch, last_n_tokens_size, lora_base, lora_path, low_vram, tensor_split, rope_freq_base, rope_freq_scale, n_gqa, rms_norm_eps, mul_mat_q, verbose)
    321                     self.model_path.encode("utf-8"), self.params
    322                 )
--> 323         assert self.model is not None
    324 
    325         if verbose:

AssertionError:
```
Thank You.

**Comment by reddiamond1234** [comment]
@brrbaral it seems like your model is not latest GGML (GGJTv3) version. Check for another conversion python script or just use another model

**Comment by brrbaral** [comment]
@reddiamond1234  thank you for your response. 
But I am getting errors even if I am using GGUF models. 
I tried downloading this model
`https://huggingface.co/TheBloke/Speechless-Llama2-13B-GGUF`
and use it as : 
```
model_path='/content/Speechless-Llama2-13B-GGUF'
from llama_cpp import Llama
llm = Llama(model_path=model_path)
output = llm("Q: Name the planets in the solar system? A: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
print(output)
```
The error is : 
```
AssertionError                            Traceback (most recent call last)
[<ipython-input-3-43beb2eceab3>](https://localhost:8080/#) in <cell line: 4>()
      2 model_path='/content/Speechless-Llama2-13B-GGUF'
      3 from llama_cpp import Llama
----> 4 llm = Llama(model_path=model_path)
      5 output = llm("Q: Name the planets in the solar system? A: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
      6 print(output)

[/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py](https://localhost:8080/#) in __init__(self, model_path, n_ctx, n_parts, n_gpu_layers, seed, f16_kv, logits_all, vocab_only, use_mmap, use_mlock, embedding, n_threads, n_batch, last_n_tokens_size, lora_base, lora_path, low_vram, tensor_split, rope_freq_base, rope_freq_scale, n_gqa, rms_norm_eps, mul_mat_q, verbose)
    321                     self.model_path.encode("utf-8"), self.params
    322                 )
--> 323         assert self.model is not None
    324 
    325         if verbose:

AssertionError:
```

**Comment by reddiamond1234** [comment]
@brrbaral ah, I see. problem is with your model path. you need to add '.bin' to this line  <code>model_path='/content/Speechless-Llama2-13B-GGUF'</code>, then it should work

**Comment by brrbaral** [comment]
Doing so, error: model path does not exist. 
```
model_path='/content/Speechless-Llama2-13B-GGUF.bin'
from llama_cpp import Llama
llm = Llama(model_path=model_path)
output = llm("Q: Name the planets in the solar system? A: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
print(output)
```
Error message: 
```
ValueError                                Traceback (most recent call last)
[<ipython-input-6-0527d9bc94eb>](https://localhost:8080/#) in <cell line: 4>()
      2 model_path='/content/Speechless-Llama2-13B-GGUF.bin'
      3 from llama_cpp import Llama
----> 4 llm = Llama(model_path=model_path)
      5 output = llm("Q: Name the planets in the solar system? A: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
      6 print(output)

[/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py](https://localhost:8080/#) in __init__(self, model_path, n_ctx, n_parts, n_gpu_layers, seed, f16_kv, logits_all, vocab_only, use_mmap, use_mlock, embedding, n_threads, n_batch, last_n_tokens_size, lora_base, lora_path, low_vram, tensor_split, rope_freq_base, rope_freq_scale, n_gqa, rms_norm_eps, mul_mat_q, verbose)
    310 
    311         if not os.path.exists(model_path):
--> 312             raise ValueError(f"Model path does not exist: {model_path}")
    313 
    314         if verbose:

ValueError: Model path does not exist: /content/Speechless-Llama2-13B-GGUF.bin
```

**Comment by reddiamond1234** [comment]
Then check again if path to your model is correct. Maybe try to put your model in folder inside your project and try again...

**Comment by brrbaral** [comment]
@reddiamond1234 I tried that as well. But did not work.

**Comment by pchalasani** [comment]
I think it will help to have instructions on where the `[..].bin` files come from. E.g. when I download a model here, I get a dir of several `gguf` files.
https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/tree/main

**Comment by AayushSameerShah** [comment]
It will be nice to convert the model to **GGUF** if they aren't available already, but hey if you want all Llama-2 models **ready**, converted to the GGUF format then check this link: https://github.com/ggerganov/llama.cpp#obtaining-and-using-the-facebook-llama-2-model

TheBloke has already published all models in the GGUF and you can use them with breeze.

![image](https://github.com/abetlen/llama-cpp-python/assets/83115948/ac7198ac-96f4-4990-94de-56430cb2e969)
