### ISSUE TITLE
Problem with the CMake installation, aborting build. 

### ISSUE THREAD

**Issue by chrfthr** [abetlen/llama-cpp-python#698]
**Installation command (conda environment):**

CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python

**produces the following output:**

Collecting llama-cpp-python
  Using cached llama_cpp_python-0.1.84.tar.gz (1.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typing-extensions>=4.5.0 (from llama-cpp-python)
  Obtaining dependency information for typing-extensions>=4.5.0 from https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl.metadata
  Using cached typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
Collecting numpy>=1.20.0 (from llama-cpp-python)
  Obtaining dependency information for numpy>=1.20.0 from https://files.pythonhosted.org/packages/32/6a/65dbc57a89078af9ff8bfcd4c0761a50172d90192eaeb1b6f56e5fbf1c3d/numpy-1.25.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached numpy-1.25.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Collecting diskcache>=5.6.1 (from llama-cpp-python)
  Obtaining dependency information for diskcache>=5.6.1 from https://files.pythonhosted.org/packages/3f/27/4570e78fc0bf5ea0ca45eb1de3818a23787af9b390c0b0a0033a1b8236f9/diskcache-5.6.3-py3-none-any.whl.metadata
  Using cached diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Using cached diskcache-5.6.3-py3-none-any.whl (45 kB)
Using cached numpy-1.25.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-czvnyoqc/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
          cmkr = cmaker.CMaker(cmake_executable)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-czvnyoqc/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 148, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-czvnyoqc/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
          raise SKBuildError(msg) from err

      Problem with the CMake installation, aborting build. CMake executable is /tmp/pip-build-env-czvnyoqc/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

```
CentOS Linux release 7.9.2009
Python 3.11.4
Make 4.2.1
devtoolkit-10 (gcc 10.2.1)
```

Llama.cpp compiles and runs succesfully with cmake3 and make.

**Comment by CaptainException** [comment]
Try running ```pip install --upgrade cmake```

For me the installation process kept succeeding without returning any errors when trying to install with cuBLAS, but GPU acceleration simply did not work. It only started using hardware acceleration after i installed all requirements which are found in the [docker example](https://github.com/abetlen/llama-cpp-python/blob/main/docker/cuda_simple/Dockerfile):
```py
# Install depencencies
RUN python3 -m pip install --upgrade pip pytest cmake scikit-build setuptools fastapi uvicorn sse-starlette pydantic-settings
```

I have no idea if all those dependencies are actually necessary as none of them is referenced in the README, but since the instruction in the README are not working i simply ran ```pip install --upgrade -r requirements.txt``` after writing all the requirements into a requirements.txt:
```py
pip
pytest
cmake
scikit-build
setuptools
fastapi
uvicorn
sse-starlette
pydantic-settings
```

After installing the requirements I ran:
```bash
$ export FORCE_CMAKE=1
$ export CMAKE_ARGS="-DLLAMA_CUBLAS=on"
$ pip install llama-cpp-python --force-reinstall --no-cache-dir
```

And now all my 4 GPUs are recognized and the whole model (~8GB) is offloaded to the main GPU.

**Comment by Ph0rk0z** [comment]
the force cmake stuff is getting removed from the readme according to changelog.

**Comment by abetlen** [comment]
@chrfthr can you post a `--verbose` installation log? This output above doesn't include the origin of the build error

**Comment by acewong7** [comment]
> Try running `pip install --upgrade cmake`
> 
> For me the installation process kept succeeding without returning any errors when trying to install with cuBLAS, but GPU acceleration simply did not work. It only started using hardware acceleration after i installed all requirements which are found in the [docker example](https://github.com/abetlen/llama-cpp-python/blob/main/docker/cuda_simple/Dockerfile):
> 
> ```python
> # Install depencencies
> RUN python3 -m pip install --upgrade pip pytest cmake scikit-build setuptools fastapi uvicorn sse-starlette pydantic-settings
> ```
> 
> I have no idea if all of those dependencies are actually necessary, as none of them is referenced in the README, but since the instructions in the README are not working, I simply ran `pip install --upgrade -r requirements.txt` after writing all the requirements into a requirements.txt:
> 
> ```python
> pip
> pytest
> cmake
> scikit-build
> setuptools
> fastapi
> uvicorn
> sse-starlette
> pydantic-settings
> ```
> 
> After installing the requirements I ran:
> 
> ```shell
> $ export FORCE_CMAKE=1
> $ export CMAKE_ARGS="-DLLAMA_CUBLAS=on"
> $ pip install llama-cpp-python --force-reinstall --no-cache-dir
> ```
> 
> And now all my 4 GPUs are recognized and the whole model (~8GB) is offloaded to the main GPU.

hello, CaptainException. I followed your suggestions and did the same commands but still have the same error which complains CMake Error, Any suggestions to resolve this problem? Many thanks.

(privategpt) [tsinghua@localhost privateGPT]$ pip install --upgrade -r requirements.txt
Requirement already satisfied: pip in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (24.0)
Requirement already satisfied: pytest in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (8.0.1)
Requirement already satisfied: cmake in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (3.28.3)
Requirement already satisfied: scikit-build in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (0.17.6)
Requirement already satisfied: setuptools in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (69.1.0)
Requirement already satisfied: fastapi in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (0.109.2)
Requirement already satisfied: uvicorn in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (0.27.1)
Requirement already satisfied: sse-starlette in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (2.0.0)
Requirement already satisfied: pydantic-settings in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (2.2.1)
Requirement already satisfied: iniconfig in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from pytest->-r requirements.txt (line 2)) (2.0.0)
Requirement already satisfied: packaging in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from pytest->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: pluggy<2.0,>=1.3.0 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from pytest->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: distro in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from scikit-build->-r requirements.txt (line 4)) (1.8.0)
Requirement already satisfied: wheel>=0.32.0 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from scikit-build->-r requirements.txt (line 4)) (0.41.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from fastapi->-r requirements.txt (line 6)) (2.5.2)
Requirement already satisfied: starlette<0.37.0,>=0.36.3 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from fastapi->-r requirements.txt (line 6)) (0.36.3)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from fastapi->-r requirements.txt (line 6)) (4.9.0)
Requirement already satisfied: click>=7.0 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from uvicorn->-r requirements.txt (line 7)) (8.1.7)
Requirement already satisfied: h11>=0.8 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from uvicorn->-r requirements.txt (line 7)) (0.14.0)
Requirement already satisfied: anyio in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from sse-starlette->-r requirements.txt (line 8)) (3.7.1)
Requirement already satisfied: python-dotenv>=0.21.0 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from pydantic-settings->-r requirements.txt (line 9)) (1.0.0)
Requirement already satisfied: annotated-types>=0.4.0 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi->-r requirements.txt (line 6)) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.5 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi->-r requirements.txt (line 6)) (2.14.5)
Requirement already satisfied: idna>=2.8 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from anyio->sse-starlette->-r requirements.txt (line 8)) (3.6)
Requirement already satisfied: sniffio>=1.1 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from anyio->sse-starlette->-r requirements.txt (line 8)) (1.3.0)
(privategpt) [tsinghua@localhost privateGPT]$ export FORCE_CMAKE=1
(privategpt) [tsinghua@localhost privateGPT]$ export CMAKE_ARGS="-DLLAMA_CUBLAS=on"
(privategpt) [tsinghua@localhost privateGPT]$ pip install llama-cpp-python --force-reinstall --no-cache-dir
Collecting llama-cpp-python
  Downloading llama_cpp_python-0.2.44.tar.gz (36.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.6/36.6 MB 8.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typing-extensions>=4.5.0 (from llama-cpp-python)
  Downloading typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting numpy>=1.20.0 (from llama-cpp-python)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 120.7 kB/s eta 0:00:00
Collecting diskcache>=5.6.1 (from llama-cpp-python)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting jinja2>=2.11.3 (from llama-cpp-python)
  Downloading Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB)
Collecting MarkupSafe>=2.0 (from jinja2>=2.11.3->llama-cpp-python)
  Downloading MarkupSafe-2.1.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 203.9 MB/s eta 0:00:00
Downloading Jinja2-3.1.3-py3-none-any.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.2/133.2 kB 77.1 kB/s eta 0:00:00
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 4.7 MB/s eta 0:00:00
Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Downloading MarkupSafe-2.1.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (28 kB)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      *** scikit-build-core 0.8.1 using CMake 3.28.3 (wheel)
      *** Configuring CMake...
      2024-02-20 21:47:54,795 - scikit_build_core - WARNING - libdir/ldlibrary: /home/tsinghua/anaconda3/envs/privategpt/lib/libpython3.11.a is not a real file!
      2024-02-20 21:47:54,795 - scikit_build_core - WARNING - Can't find a Python library, got libdir=/home/tsinghua/anaconda3/envs/privategpt/lib, ldlibrary=libpython3.11.a, multiarch=x86_64-linux-gnu, masd=None
      loading initial cache file /tmp/tmp917xntf4/build/CMakeInit.txt
      -- The C compiler identification is GNU 4.8.5
      -- The CXX compiler identification is GNU 4.8.5
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Git: /usr/bin/git (found version "1.8.3.1")
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Check if compiler accepts -pthread
      -- Check if compiler accepts -pthread - yes
      -- Found Threads: TRUE
      -- Found CUDAToolkit: /usr/local/cuda/targets/x86_64-linux/include (found version "12.3.107")
      -- cuBLAS found
      -- The CUDA compiler identification is unknown
      CMake Error at /tmp/pip-build-env-v5hnhc1z/normal/lib/python3.11/site-packages/cmake/data/share/cmake-3.28/Modules/CMakeDetermineCUDACompiler.cmake:270 (message):
        Failed to detect a default CUDA architecture.



        Compiler output:

      Call Stack (most recent call first):
        vendor/llama.cpp/CMakeLists.txt:327 (enable_language)


      -- Configuring incomplete, errors occurred!

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

**Comment by acewong7** [comment]
> > Try running `pip install --upgrade cmake`
> > For me the installation process kept succeeding without returning any errors when trying to install with cuBLAS, but GPU acceleration simply did not work. It only started using hardware acceleration after i installed all requirements which are found in the [docker example](https://github.com/abetlen/llama-cpp-python/blob/main/docker/cuda_simple/Dockerfile):
> > ```python
> > # Install depencencies
> > RUN python3 -m pip install --upgrade pip pytest cmake scikit-build setuptools fastapi uvicorn sse-starlette pydantic-settings
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have no idea if all of those dependencies are actually necessary, as none of them is referenced in the README, but since the instructions in the README are not working, I simply ran `pip install --upgrade -r requirements.txt` after writing all the requirements into a requirements.txt:
> > ```python
> > pip
> > pytest
> > cmake
> > scikit-build
> > setuptools
> > fastapi
> > uvicorn
> > sse-starlette
> > pydantic-settings
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After installing the requirements I ran:
> > ```shell
> > $ export FORCE_CMAKE=1
> > $ export CMAKE_ARGS="-DLLAMA_CUBLAS=on"
> > $ pip install llama-cpp-python --force-reinstall --no-cache-dir
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And now all my 4 GPUs are recognized and the whole model (~8GB) is offloaded to the main GPU.
> 
> hello, CaptainException. I followed your suggestions and did the same commands but still have the same error which complains CMake Error, Any suggestions to resolve this problem? Many thanks.
> 
> (privategpt) [tsinghua@localhost privateGPT]$ pip install --upgrade -r requirements.txt Requirement already satisfied: pip in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (24.0) Requirement already satisfied: pytest in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (8.0.1) Requirement already satisfied: cmake in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (3.28.3) Requirement already satisfied: scikit-build in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (0.17.6) Requirement already satisfied: setuptools in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (69.1.0) Requirement already satisfied: fastapi in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (0.109.2) Requirement already satisfied: uvicorn in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (0.27.1) Requirement already satisfied: sse-starlette in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (2.0.0) Requirement already satisfied: pydantic-settings in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (2.2.1) Requirement already satisfied: iniconfig in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from pytest->-r requirements.txt (line 2)) (2.0.0) Requirement already satisfied: packaging in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from pytest->-r requirements.txt (line 2)) (23.2) Requirement already satisfied: pluggy<2.0,>=1.3.0 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from pytest->-r requirements.txt (line 2)) (1.3.0) Requirement already satisfied: distro in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from scikit-build->-r requirements.txt (line 4)) (1.8.0) Requirement already satisfied: wheel>=0.32.0 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from scikit-build->-r requirements.txt (line 4)) (0.41.2) Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from fastapi->-r requirements.txt (line 6)) (2.5.2) Requirement already satisfied: starlette<0.37.0,>=0.36.3 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from fastapi->-r requirements.txt (line 6)) (0.36.3) Requirement already satisfied: typing-extensions>=4.8.0 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from fastapi->-r requirements.txt (line 6)) (4.9.0) Requirement already satisfied: click>=7.0 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from uvicorn->-r requirements.txt (line 7)) (8.1.7) Requirement already satisfied: h11>=0.8 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from uvicorn->-r requirements.txt (line 7)) (0.14.0) Requirement already satisfied: anyio in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from sse-starlette->-r requirements.txt (line 8)) (3.7.1) Requirement already satisfied: python-dotenv>=0.21.0 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from pydantic-settings->-r requirements.txt (line 9)) (1.0.0) Requirement already satisfied: annotated-types>=0.4.0 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi->-r requirements.txt (line 6)) (0.6.0) Requirement already satisfied: pydantic-core==2.14.5 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi->-r requirements.txt (line 6)) (2.14.5) Requirement already satisfied: idna>=2.8 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from anyio->sse-starlette->-r requirements.txt (line 8)) (3.6) Requirement already satisfied: sniffio>=1.1 in /home/tsinghua/anaconda3/envs/privategpt/lib/python3.11/site-packages (from anyio->sse-starlette->-r requirements.txt (line 8)) (1.3.0) (privategpt) [tsinghua@localhost privateGPT]$ export FORCE_CMAKE=1 (privategpt) [tsinghua@localhost privateGPT]$ export CMAKE_ARGS="-DLLAMA_CUBLAS=on" (privategpt) [tsinghua@localhost privateGPT]$ pip install llama-cpp-python --force-reinstall --no-cache-dir Collecting llama-cpp-python Downloading llama_cpp_python-0.2.44.tar.gz (36.6 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.6/36.6 MB 8.5 MB/s eta 0:00:00 Installing build dependencies ... done Getting requirements to build wheel ... done Installing backend dependencies ... done Preparing metadata (pyproject.toml) ... done Collecting typing-extensions>=4.5.0 (from llama-cpp-python) Downloading typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB) Collecting numpy>=1.20.0 (from llama-cpp-python) Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 120.7 kB/s eta 0:00:00 Collecting diskcache>=5.6.1 (from llama-cpp-python) Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB) Collecting jinja2>=2.11.3 (from llama-cpp-python) Downloading Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB) Collecting MarkupSafe>=2.0 (from jinja2>=2.11.3->llama-cpp-python) Downloading MarkupSafe-2.1.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB) Downloading diskcache-5.6.3-py3-none-any.whl (45 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 203.9 MB/s eta 0:00:00 Downloading Jinja2-3.1.3-py3-none-any.whl (133 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.2/133.2 kB 77.1 kB/s eta 0:00:00 Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 4.7 MB/s eta 0:00:00 Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB) Downloading MarkupSafe-2.1.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (28 kB) Building wheels for collected packages: llama-cpp-python Building wheel for llama-cpp-python (pyproject.toml) ... error error: subprocess-exited-with-error
> 
> × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [40 lines of output] *** scikit-build-core 0.8.1 using CMake 3.28.3 (wheel) *** Configuring CMake... 2024-02-20 21:47:54,795 - scikit_build_core - WARNING - libdir/ldlibrary: /home/tsinghua/anaconda3/envs/privategpt/lib/libpython3.11.a is not a real file! 2024-02-20 21:47:54,795 - scikit_build_core - WARNING - Can't find a Python library, got libdir=/home/tsinghua/anaconda3/envs/privategpt/lib, ldlibrary=libpython3.11.a, multiarch=x86_64-linux-gnu, masd=None loading initial cache file /tmp/tmp917xntf4/build/CMakeInit.txt -- The C compiler identification is GNU 4.8.5 -- The CXX compiler identification is GNU 4.8.5 -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Check for working C compiler: /usr/bin/cc - skipped -- Detecting C compile features -- Detecting C compile features - done -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Check for working CXX compiler: /usr/bin/c++ - skipped -- Detecting CXX compile features -- Detecting CXX compile features - done -- Found Git: /usr/bin/git (found version "1.8.3.1") -- Performing Test CMAKE_HAVE_LIBC_PTHREAD -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed -- Check if compiler accepts -pthread -- Check if compiler accepts -pthread - yes -- Found Threads: TRUE -- Found CUDAToolkit: /usr/local/cuda/targets/x86_64-linux/include (found version "12.3.107") -- cuBLAS found -- The CUDA compiler identification is unknown CMake Error at /tmp/pip-build-env-v5hnhc1z/normal/lib/python3.11/site-packages/cmake/data/share/cmake-3.28/Modules/CMakeDetermineCUDACompiler.cmake:270 (message): Failed to detect a default CUDA architecture.
> 
> ```
>     Compiler output:
> 
>   Call Stack (most recent call first):
>     vendor/llama.cpp/CMakeLists.txt:327 (enable_language)
> 
> 
>   -- Configuring incomplete, errors occurred!
> 
>   *** CMake configuration failed
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for llama-cpp-python Failed to build llama-cpp-python ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

here is the screenshot with the CMake error in color.
![image](https://github.com/abetlen/llama-cpp-python/assets/16329701/91e5bc2d-56bd-4ed9-94ed-654705fb003c)

**Comment by kanamadiharshita** [comment]
cmake version 3.29 python3.12 llama-cpp-python=0.2.57
llm = Llama(
            model_path="./PG_dir/mistral-7b-instruct-v0.1.Q4_K_M.gguf",
    # model_type="mistral",
    # temperature=0.3,
    # max_new_tokens = 50
    config={"max_new_tokens": 500, "context_length": 4096, "temperature": 0.3},

    )

i am getting error ValueError: Model path does not exist: ./PG_dir/mistral-7b-instruct-v0.1.Q4_K_M.gguf

**Comment by kanamadiharshita** [comment]
cmake version 3.29 python3.12 llama-cpp-python=0.2.57
llm = Llama(
            model_path="./PG_dir/mistral-7b-instruct-v0.1.Q4_K_M.gguf",
    # model_type="mistral",
    # temperature=0.3,
    # max_new_tokens = 50
    config={"max_new_tokens": 500, "context_length": 4096, "temperature": 0.3},

    )

i am getting error ValueError: Model path does not exist: ./PG_dir/mistral-7b-instruct-v0.1.Q4_K_M.gguf
