### ISSUE TITLE
Missing starlette-context dependency in docker/*/Dockerfile

### ISSUE THREAD

**Issue by mqq-marek** [abetlen/llama-cpp-python#718]
# Expected Behavior

docker run starts server

# Current Behavior
/app/start_server.sh: 4: ulimit: error setting limit (Operation not permitted)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/server/__main__.py", line 30, in <module>
    from llama_cpp.server.app import create_app, Settings
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/server/app.py", line 22, in <module>
    from starlette_context import plugins
ModuleNotFoundError: No module named 'starlette_context'

There is also missing --n_gpu_layers=1000 parameter in docker/cuda_simple/Dockerfile

Edited:
In addition it looks that cuda_simple builds proper image for cuda while open_llama with selected cuda image not.

I can make above fixes, but it will be my first attempt to do pull request, unfortunatelly I try to do pull request but I don't know the proper workflow (shame on me).

**Comment by abetlen** [comment]
@mqq-marek pushed a fix do you mind checking that out?
