### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by adouc** [abetlen/llama-cpp-python#722]
Hello I am a complete noob so I don't know if I have provided enough informations to be helped. but I need help in this please

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ ] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [ ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ ] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

to install  `llama-cpp-python` on my MAC.

# Current Behavior

Collecting llama-cpp-python
  Using cached llama_cpp_python-0.2.5.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-cpp-python) (4.7.1)
Collecting numpy>=1.20.0 (from llama-cpp-python)
  Obtaining dependency information for numpy>=1.20.0 from https://files.pythonhosted.org/packages/c9/57/3cb8131a0e6d559501e088d3e685f4122e9ff9104c4b63e4dfd3a577b491/numpy-1.25.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Using cached numpy-1.25.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (5.6 kB)
Collecting diskcache>=5.6.1 (from llama-cpp-python)
  Obtaining dependency information for diskcache>=5.6.1 from https://files.pythonhosted.org/packages/3f/27/4570e78fc0bf5ea0ca45eb1de3818a23787af9b390c0b0a0033a1b8236f9/diskcache-5.6.3-py3-none-any.whl.metadata
  Using cached diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Using cached diskcache-5.6.3-py3-none-any.whl (45 kB)
Using cached numpy-1.25.2-cp311-cp311-macosx_10_9_x86_64.whl (20.8 MB)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      *** scikit-build-core 0.5.0 using CMake 3.27.4 (wheel)
      *** Configuring CMake...
      2023-09-15 15:15:22,896 - scikit_build_core - WARNING - libdir/ldlibrary: /Library/Frameworks/Python.framework/Versions/3.11/lib/Python.framework/Versions/3.11/Python is not a real file!
      loading initial cache file /tmp/tmpc9djzsbq/build/CMakeInit.txt
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      -- The C compiler identification is unknown
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      -- The CXX compiler identification is unknown
      sh: ps: command not found
      CMake Error at CMakeLists.txt:3 (project):
        No CMAKE_C_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.
      
      
      CMake Error at CMakeLists.txt:3 (project):
        No CMAKE_CXX_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      
      *** CMake configuration failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
Error during installation with Metal: Command '['/Library/Frameworks/Python.framework/Versions/3.11/bin/python3', '-m', 'pip', 'install', 'llama-cpp-python']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/get_hf_llm.py", line 141, in get_hf_llm
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/interpreter.py", line 203, in chat
    self.llama_instance = get_hf_llm(self.model, self.debug_mode, self.context_window)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/get_hf_llm.py", line 200, in get_hf_llm
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

▌ Failed to install TheBloke/CodeLlama-34B-Instruct-GGUF.

**Comment by luyanxiao** [comment]
+1, face the same issue on my laptop

**Comment by adouc** [comment]
> +1, face the same issue on my laptop

Sorry to hear about that. Did you find a solution?
