### ISSUE TITLE
FileNotFoundError: Shared library with base name 'llama' not found #MACOS

### ISSUE THREAD

**Issue by Showwwwwwwww** [abetlen/llama-cpp-python#739]
Hi,
I am trying to run it on my mac, however it shows that cannot find the shared libray "llama"

Here is the error message. 
`
(llama) chen@chenshuodeMBP-9 llama-cpp-python % python3 -m llama_cpp.server --model $MODEL  --n_gpu_layers 1
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/chen/Desktop/robot/robot_research/llama2/llama-cpp-python/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/Users/chen/Desktop/robot/robot_research/llama2/llama-cpp-python/llama_cpp/llama_cpp.py", line 80, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chen/Desktop/robot/robot_research/llama2/llama-cpp-python/llama_cpp/llama_cpp.py", line 71, in _load_shared_library
    raise FileNotFoundError(
FileNotFoundError: Shared library with base name 'llama' not found`

Can I know how to fix it?

Thanks

**Comment by abetlen** [comment]
@Showwwwwwwww can you reinstall with `--verbose` and past a log here?

**Comment by vanpelt** [comment]
I'm getting the same error when using the official docker image on my M1 Mac.  I just ran `pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir --verbose` from inside the container.  I'm not seeing any errors, it seems to build successfully with a few warnings.  I also attached the stacktrace I'm getting on import.

```
Building wheels for collected packages: llama-cpp-python
  Running command Building wheel for llama-cpp-python (pyproject.toml)
  *** scikit-build-core 0.5.1 using CMake 3.27.6 (wheel)
  *** Configuring CMake...
  loading initial cache file /tmp/tmp7rhl4t08/build/CMakeInit.txt
  -- The C compiler identification is GNU 10.2.1
  -- The CXX compiler identification is GNU 10.2.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Could NOT find Git (missing: GIT_EXECUTABLE)
  CMake Warning at vendor/llama.cpp/scripts/build-info.cmake:16 (message):
    Git not found.  Build info will not be accurate.
  Call Stack (most recent call first):
    vendor/llama.cpp/CMakeLists.txt:102 (include)


  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Check if compiler accepts -pthread
  -- Check if compiler accepts -pthread - yes
  -- Found Threads: TRUE
  -- CMAKE_SYSTEM_PROCESSOR: aarch64
  -- ARM detected
  -- Performing Test COMPILER_SUPPORTS_FP16_FORMAT_I3E
  -- Performing Test COMPILER_SUPPORTS_FP16_FORMAT_I3E - Failed
  CMake Warning (dev) at CMakeLists.txt:18 (install):
    Target llama has PUBLIC_HEADER files but no PUBLIC_HEADER DESTINATION.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning (dev) at CMakeLists.txt:27 (install):
    Target llama has PUBLIC_HEADER files but no PUBLIC_HEADER DESTINATION.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  -- Configuring done (0.3s)
  -- Generating done (0.0s)
  -- Build files have been written to: /tmp/tmp7rhl4t08/build
  *** Building project with Ninja...
  Change Dir: '/tmp/tmp7rhl4t08/build'

  Run Build Command(s): /usr/bin/ninja -v
  [1/12] cd /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp && /tmp/pip-build-env-i57760r0/normal/lib/python3.11/site-packages/cmake/data/bin/cmake -DMSVC= -DCMAKE_C_COMPILER_VERSION=10.2.1 -DCMAKE_C_COMPILER_ID=GNU -DCMAKE_VS_PLATFORM_NAME= -DCMAKE_C_COMPILER=/usr/bin/cc -P /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/scripts/build-info.cmake
  -- Could NOT find Git (missing: GIT_EXECUTABLE)
  CMake Warning at scripts/build-info.cmake:16 (message):
    Git not found.  Build info will not be accurate.


  [2/12] /usr/bin/cc -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -Wdouble-promotion -pthread -MD -MT vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-alloc.c.o -MF vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-alloc.c.o.d -o vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-alloc.c.o -c /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/ggml-alloc.c
  [3/12] /usr/bin/c++ -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/common/. -I/tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Wno-array-bounds -Wno-format-truncation -Wextra-semi -MD -MT vendor/llama.cpp/common/CMakeFiles/common.dir/console.cpp.o -MF vendor/llama.cpp/common/CMakeFiles/common.dir/console.cpp.o.d -o vendor/llama.cpp/common/CMakeFiles/common.dir/console.cpp.o -c /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/common/console.cpp
  [4/12] /usr/bin/c++ -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/common/. -I/tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Wno-array-bounds -Wno-format-truncation -Wextra-semi -MD -MT vendor/llama.cpp/common/CMakeFiles/common.dir/grammar-parser.cpp.o -MF vendor/llama.cpp/common/CMakeFiles/common.dir/grammar-parser.cpp.o.d -o vendor/llama.cpp/common/CMakeFiles/common.dir/grammar-parser.cpp.o -c /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/common/grammar-parser.cpp
  [5/12] /usr/bin/cc -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -Wdouble-promotion -pthread -MD -MT vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o -MF vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o.d -o vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o -c /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/k_quants.c
  /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/k_quants.c: In function ‘ggml_vec_dot_q2_K_q8_K’:
  /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/k_quants.c:1356:36: warning: missing braces around initializer [-Wmissing-braces]
   1356 |         const int16x8x2_t mins16 = {vreinterpretq_s16_u16(vmovl_u8(vget_low_u8(mins))), vreinterpretq_s16_u16(vmovl_u8(vget_high_u8(mins)))};
        |                                    ^
        |                                     {                                                                                                      }
  /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/k_quants.c: In function ‘ggml_vec_dot_q6_K_q8_K’:
  /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/k_quants.c:3717:38: warning: missing braces around initializer [-Wmissing-braces]
   3717 |         const int16x8x2_t q6scales = {vmovl_s8(vget_low_s8(scales)), vmovl_s8(vget_high_s8(scales))};
        |                                      ^
        |                                       {                                                            }
  [6/12] /usr/bin/c++ -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/common/. -I/tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Wno-array-bounds -Wno-format-truncation -Wextra-semi -MD -MT vendor/llama.cpp/common/CMakeFiles/common.dir/train.cpp.o -MF vendor/llama.cpp/common/CMakeFiles/common.dir/train.cpp.o.d -o vendor/llama.cpp/common/CMakeFiles/common.dir/train.cpp.o -c /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/common/train.cpp
  [7/12] /usr/bin/c++ -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/common/. -I/tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Wno-array-bounds -Wno-format-truncation -Wextra-semi -MD -MT vendor/llama.cpp/common/CMakeFiles/common.dir/common.cpp.o -MF vendor/llama.cpp/common/CMakeFiles/common.dir/common.cpp.o.d -o vendor/llama.cpp/common/CMakeFiles/common.dir/common.cpp.o -c /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/common/common.cpp
  [8/12] /usr/bin/cc -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -Wdouble-promotion -pthread -MD -MT vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o -MF vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o.d -o vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o -c /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/ggml.c
  [9/12] : && /tmp/pip-build-env-i57760r0/normal/lib/python3.11/site-packages/cmake/data/bin/cmake -E rm -f vendor/llama.cpp/libggml_static.a && /usr/bin/ar qc vendor/llama.cpp/libggml_static.a  vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-alloc.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o && /usr/bin/ranlib vendor/llama.cpp/libggml_static.a && :
  [10/12] : && /usr/bin/cc -fPIC -O3 -DNDEBUG   -shared -Wl,-soname,libggml_shared.so -o vendor/llama.cpp/libggml_shared.so vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-alloc.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o  -pthread && :
  [11/12] /usr/bin/c++ -DGGML_USE_K_QUANTS -DLLAMA_BUILD -DLLAMA_SHARED -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -Dllama_EXPORTS -I/tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Wno-array-bounds -Wno-format-truncation -Wextra-semi -pthread -MD -MT vendor/llama.cpp/CMakeFiles/llama.dir/llama.cpp.o -MF vendor/llama.cpp/CMakeFiles/llama.dir/llama.cpp.o.d -o vendor/llama.cpp/CMakeFiles/llama.dir/llama.cpp.o -c /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/vendor/llama.cpp/llama.cpp
  [12/12] : && /usr/bin/c++ -fPIC -O3 -DNDEBUG   -shared -Wl,-soname,libllama.so -o vendor/llama.cpp/libllama.so vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-alloc.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o vendor/llama.cpp/CMakeFiles/llama.dir/llama.cpp.o  -pthread && :

  *** Installing project into wheel...
  -- Install configuration: "Release"
  -- Installing: /tmp/tmp7rhl4t08/wheel/platlib/lib/libggml_shared.so
  -- Installing: /tmp/tmp7rhl4t08/wheel/platlib/lib/cmake/Llama/LlamaConfig.cmake
  -- Installing: /tmp/tmp7rhl4t08/wheel/platlib/lib/cmake/Llama/LlamaConfigVersion.cmake
  -- Installing: /tmp/tmp7rhl4t08/wheel/platlib/include/ggml.h
  -- Installing: /tmp/tmp7rhl4t08/wheel/platlib/include/k_quants.h
  -- Installing: /tmp/tmp7rhl4t08/wheel/platlib/lib/libllama.so
  -- Installing: /tmp/tmp7rhl4t08/wheel/platlib/include/llama.h
  -- Installing: /tmp/tmp7rhl4t08/wheel/platlib/bin/convert.py
  -- Installing: /tmp/tmp7rhl4t08/wheel/platlib/bin/convert-lora-to-ggml.py
  -- Installing: /tmp/tmp7rhl4t08/wheel/platlib/llama_cpp/libllama.so
  -- Installing: /tmp/pip-install-akimavjw/llama-cpp-python_20d39405dcf343b6963876e26f6baa24/llama_cpp/libllama.so
  *** Making wheel...
  *** Created llama_cpp_python-0.2.11-cp311-cp311-manylinux_2_31_aarch64.whl...
  Building wheel for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.2.11-cp311-cp311-manylinux_2_31_aarch64.whl size=932793 sha256=a030c934c888499045acfa7ebf351a28cbd12ac6601fa6cc785948503b57a68c
  Stored in directory: /tmp/pip-ephem-wheel-cache-vihvefa_/wheels/f2/35/aa/ae233f34d3f2db880f078f01c4ab535f1674bebab171b5c808
  ```
  
  Import error:
  
  ```
  Traceback (most recent call last):
  File "/app/evaluate.py", line 3, in <module>
    from llama_cpp import Llama
  File "/app/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/app/llama_cpp/llama_cpp.py", line 81, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/llama_cpp/llama_cpp.py", line 72, in _load_shared_library
    raise FileNotFoundError(
FileNotFoundError: Shared library with base name 'llama' not found
  ```

**Comment by vanpelt** [comment]
I did some more debugging.  My issue is the same as #568 .  The latest docker container has the library itself in `/app/llama_cpp` but libllama.so is in site packages.  I added the following line to my Dockerfile and it fixed the issue:

```
RUN cp /usr/local/lib/python3.11/site-packages/llama_cpp/libllama.so /app/llama_cpp
```

I imagine the docker build should just put everything in site-packages and blow away the `/app` directory as it's a common place for users of the image to put their own code.  If I have time I'll take a pass at refactoring the Dockerfile.

**Comment by jmtatsch** [comment]
@vanpelt I have the same issue but /usr/local/lib/python3.11/site-packages/llama_cpp/libllama.so doesn't even seem to exist at that place.
Nevertheless I think it would be cleaner to make the library path known instead of copying around libraries.
ENV LD_LIBRARY_PATH=/usr/local/lib/python3.11/site-packages/
Does that work for you?

**Comment by vanpelt** [comment]
@jmtatsch the weird thing was none of the python code was in my `/usr/local/lib/python3.11/site-packages/llama_cpp/` directory, it only contained the shared library 🤔

**Comment by jmtatsch** [comment]
There is a bug that bin and other directories of the package are in the parent folder where they don't belong. There is already a pull request open for that.
