### ISSUE TITLE
Destructor error in llama.py - LlamaCpp

### ISSUE THREAD

**Issue by sherwin684** [abetlen/llama-cpp-python#806]
# Expected Behavior

I am using a lanchain wrapper to import LlamaCpp as follows:
`from langchain.llms import LlamaCpp`

# Current Behavior

When my script using this class ends, I get a `NoneType` object not callable error.

`Exception ignored in: <function Llama.__del__ at 0x7fa2fc2224d0>
Traceback (most recent call last):
  File "/home/ubuntu/my_data/01_python/OPS-LLM/LLM_OPS/llm_ops_env/lib/python3.10/site-packages/llama_cpp/llama.py", line 1658, in __del__
TypeError: 'NoneType' object is not callable`

# Environment and Context

I am running python 3.10.9 with langchain = 0.0.306 and llama_cpp_python = 0.2.11

**Comment by dudkiina** [comment]
Update your version of langchain.

**Comment by stofarius** [comment]
I am using langchain 0.0.315 and I have the same error.

**Comment by sherwin684** [comment]
I just commented a few lines around line 1658 in `lib/python3.10/site-packages/llama_cpp/llama.py` and it solved the issue. And atleast for me it did not cause any other dependency issue.

**Comment by vodorok** [comment]
I only get this error when I use a `SentenceTransformerEmbeddings` before the llamacpp llm.

**Comment by ginnysun** [comment]
@vodorok, were you able to use a different embedding to work around this error? If so, what embedding worked for you? Thanks!

**Comment by adubkov** [comment]
I'm having similar issue with:
**llama_cpp_python 0.2.20**

```bash
Exception ignored in: <function _LlamaContext.__del__ at 0x169df7240>
Traceback (most recent call last):
  File "/Users/test/lib/python3.11/site-packages/llama_cpp/llama.py", line 422, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _LlamaModel.__del__ at 0x169df6200>
Traceback (most recent call last):
  File "/Users/test/lib/python3.11/site-packages/llama_cpp/llama.py", line 240, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _LlamaBatch.__del__ at 0x16a108720>
Traceback (most recent call last):
  File "/Users/test/lib/python3.11/site-packages/llama_cpp/llama.py", line 670, in __del__
TypeError: 'NoneType' object is not callable
```

cc @abetlen

**Comment by bradenkwebb** [comment]
Why was this closed as completed? I'm getting the same error with version 0.2.38. I know it's a very minor issue, but should still probably be addressed at some point

**Comment by abetlen** [comment]
hey @bradenkwebb sorry about that, this was supposed to be fixed in https://github.com/abetlen/llama-cpp-python/pull/846 however the current approach to logging is a little error prone / system dependant.

**Comment by mbradyneeley** [comment]
I am experiencing the same thing as others, following embedding. llama_cpp_python 0.3.1 and langchain 0.3.3

**Comment by aaron-siegel** [comment]
I'm getting this exception too.
`llama-cpp-python` 0.3.1
Python 3.9.19
MacOS 14.4.1 (M3 Max)

```
Exception ignored in: <function Llama.__del__ at 0x39d53aca0>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/pxt/lib/python3.9/site-packages/llama_cpp/llama.py", line 2202, in __del__
  File "/opt/miniconda3/envs/pxt/lib/python3.9/site-packages/llama_cpp/llama.py", line 2199, in close
  File "/opt/miniconda3/envs/pxt/lib/python3.9/contextlib.py", line 540, in close
  File "/opt/miniconda3/envs/pxt/lib/python3.9/contextlib.py", line 532, in __exit__
  File "/opt/miniconda3/envs/pxt/lib/python3.9/contextlib.py", line 517, in __exit__
  File "/opt/miniconda3/envs/pxt/lib/python3.9/contextlib.py", line 322, in __exit__
  File "/opt/miniconda3/envs/pxt/lib/python3.9/site-packages/llama_cpp/_internals.py", line 69, in close
  File "/opt/miniconda3/envs/pxt/lib/python3.9/contextlib.py", line 540, in close
  File "/opt/miniconda3/envs/pxt/lib/python3.9/contextlib.py", line 532, in __exit__
  File "/opt/miniconda3/envs/pxt/lib/python3.9/contextlib.py", line 517, in __exit__
  File "/opt/miniconda3/envs/pxt/lib/python3.9/contextlib.py", line 405, in _exit_wrapper
  File "/opt/miniconda3/envs/pxt/lib/python3.9/site-packages/llama_cpp/_internals.py", line 63, in free_model
TypeError: 'NoneType' object is not callable
```

**Comment by hg0428** [comment]
I am also getting this problem.

**Comment by aaron-siegel** [comment]
@abetlen why is this issue marked as closed if multiple users are still experiencing it?
