### ISSUE TITLE
[Request] Test LoRA API

### ISSUE THREAD

**Issue by abetlen** [abetlen/llama-cpp-python#90]
I've pushed support for the new LoRA feature of llama.cpp. This feature should allow you to load a base model and apply a LoRA adapter on-the-fly.

I haven't yet published this to PyPI as I haven't had a chance to test it. Could someone with access to a base Llama model and an adapter (ie. Alpaca LoRA) please test this out?

You should be able to
```
import llama_cpp

llama = Llama(model_path="<path-to-base-ggml-model>", lora_path="<path-to-lora-adapter>")
```

**Comment by gjmulder** [comment]
@abetlen to ensure I picked up your cache enhancement I tried to reinstall and got the error: `libllama.so: undefined symbol: llama_apply_lora_from_file
`

```
$ rm -r _skbuild/

$ git log | head -1
commit 32ca803bd8836d2595777a08cb81401a3d11a802

$ git submodule update --init --recursive

$ LLAMA_OPENBLAS=on python3 setup.py develop
/home/mulderg/anaconda3/envs/lcp/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(


--------------------------------------------------------------------------------
-- Trying 'Ninja' generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/home/mulderg/Work/llama-cpp-python/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying 'Ninja' generator - failure
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- Trying 'Unix Makefiles' generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 10.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is GNU 10.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mulderg/Work/llama-cpp-python/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying 'Unix Makefiles' generator - success
--------------------------------------------------------------------------------

Configuring Project
  Working directory:
    /home/mulderg/Work/llama-cpp-python/_skbuild/linux-x86_64-3.10/cmake-build
  Command:
    /usr/local/bin/cmake /home/mulderg/Work/llama-cpp-python -G 'Unix Makefiles' --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/home/mulderg/Work/llama-cpp-python/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.10 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/mulderg/anaconda3/envs/lcp/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/mulderg/anaconda3/envs/lcp/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/home/mulderg/anaconda3/envs/lcp/include/python3.10 -DPYTHON_LIBRARY:PATH=/home/mulderg/anaconda3/envs/lcp/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/home/mulderg/anaconda3/envs/lcp/bin/python3 -DPython_ROOT_DIR:PATH=/home/mulderg/anaconda3/envs/lcp -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/mulderg/anaconda3/envs/lcp/include/python3.10 -DPython_LIBRARY:PATH=/home/mulderg/anaconda3/envs/lcp/lib/libpython3.10.so -DPython3_EXECUTABLE:PATH=/home/mulderg/anaconda3/envs/lcp/bin/python3 -DPython3_ROOT_DIR:PATH=/home/mulderg/anaconda3/envs/lcp -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/mulderg/anaconda3/envs/lcp/include/python3.10 -DPython3_LIBRARY:PATH=/home/mulderg/anaconda3/envs/lcp/lib/libpython3.10.so -DCMAKE_BUILD_TYPE:STRING=Release

Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 10.4.0
-- The CXX compiler identification is GNU 10.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mulderg/Work/llama-cpp-python/_skbuild/linux-x86_64-3.10/cmake-build
[100%] Built target run
Install the project...
-- Install configuration: "Release"
-- Installing: /home/mulderg/Work/llama-cpp-python/_skbuild/linux-x86_64-3.10/cmake-install/llama_cpp/libllama.so
copying _skbuild/linux-x86_64-3.10/cmake-install/llama_cpp/libllama.so -> llama_cpp/libllama.so

running develop
/home/mulderg/anaconda3/envs/lcp/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing llama_cpp_python.egg-info/PKG-INFO
writing dependency_links to llama_cpp_python.egg-info/dependency_links.txt
writing requirements to llama_cpp_python.egg-info/requires.txt
writing top-level names to llama_cpp_python.egg-info/top_level.txt
reading manifest file 'llama_cpp_python.egg-info/SOURCES.txt'
adding license file 'LICENSE.md'
writing manifest file 'llama_cpp_python.egg-info/SOURCES.txt'
running build_ext
Creating /home/mulderg/anaconda3/envs/lcp/lib/python3.10/site-packages/llama-cpp-python.egg-link (link to .)
llama-cpp-python 0.1.34 is already the active version in easy-install.pth

Installed /home/mulderg/Work/llama-cpp-python
Processing dependencies for llama-cpp-python==0.1.34
Searching for typing-extensions==4.5.0
Best match: typing-extensions 4.5.0
Processing typing_extensions-4.5.0-py3.10.egg
typing-extensions 4.5.0 is already the active version in easy-install.pth

Using /home/mulderg/anaconda3/envs/lcp/lib/python3.10/site-packages/typing_extensions-4.5.0-py3.10.egg
Finished processing dependencies for llama-cpp-python==0.1.34

$ HOST=192.168.1.73 python3 -m llama_cpp.server
Traceback (most recent call last):
  File "/home/mulderg/anaconda3/envs/lcp/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/mulderg/anaconda3/envs/lcp/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/mulderg/Work/llama-cpp-python/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/home/mulderg/Work/llama-cpp-python/llama_cpp/llama_cpp.py", line 192, in <module>
    _lib.llama_apply_lora_from_file.argtypes = [llama_context_p, c_char_p, c_char_p, c_int]
  File "/home/mulderg/anaconda3/envs/lcp/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/home/mulderg/anaconda3/envs/lcp/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/mulderg/Work/llama-cpp-python/llama_cpp/libllama.so: undefined symbol: llama_apply_lora_from_file
```

**Comment by gjmulder** [comment]
@abetlen `libllama.so: undefined symbol: llama_apply_lora_from_file`

```
$ rm -r _skbuild/

$ git log | head -1
commit 32ca803bd8836d2595777a08cb81401a3d11a802

$ git submodule update --init --recursive

$ LLAMA_OPENBLAS=on python3 setup.py develop
/home/mulderg/anaconda3/envs/lcp/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(


--------------------------------------------------------------------------------
-- Trying 'Ninja' generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/home/mulderg/Work/llama-cpp-python/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying 'Ninja' generator - failure
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- Trying 'Unix Makefiles' generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 10.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is GNU 10.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mulderg/Work/llama-cpp-python/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying 'Unix Makefiles' generator - success
--------------------------------------------------------------------------------

Configuring Project
  Working directory:
    /home/mulderg/Work/llama-cpp-python/_skbuild/linux-x86_64-3.10/cmake-build
  Command:
    /usr/local/bin/cmake /home/mulderg/Work/llama-cpp-python -G 'Unix Makefiles' --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/home/mulderg/Work/llama-cpp-python/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.10 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/mulderg/anaconda3/envs/lcp/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/mulderg/anaconda3/envs/lcp/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/home/mulderg/anaconda3/envs/lcp/include/python3.10 -DPYTHON_LIBRARY:PATH=/home/mulderg/anaconda3/envs/lcp/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/home/mulderg/anaconda3/envs/lcp/bin/python3 -DPython_ROOT_DIR:PATH=/home/mulderg/anaconda3/envs/lcp -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/mulderg/anaconda3/envs/lcp/include/python3.10 -DPython_LIBRARY:PATH=/home/mulderg/anaconda3/envs/lcp/lib/libpython3.10.so -DPython3_EXECUTABLE:PATH=/home/mulderg/anaconda3/envs/lcp/bin/python3 -DPython3_ROOT_DIR:PATH=/home/mulderg/anaconda3/envs/lcp -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/mulderg/anaconda3/envs/lcp/include/python3.10 -DPython3_LIBRARY:PATH=/home/mulderg/anaconda3/envs/lcp/lib/libpython3.10.so -DCMAKE_BUILD_TYPE:STRING=Release

Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 10.4.0
-- The CXX compiler identification is GNU 10.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mulderg/Work/llama-cpp-python/_skbuild/linux-x86_64-3.10/cmake-build
[100%] Built target run
Install the project...
-- Install configuration: "Release"
-- Installing: /home/mulderg/Work/llama-cpp-python/_skbuild/linux-x86_64-3.10/cmake-install/llama_cpp/libllama.so
copying _skbuild/linux-x86_64-3.10/cmake-install/llama_cpp/libllama.so -> llama_cpp/libllama.so

running develop
/home/mulderg/anaconda3/envs/lcp/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing llama_cpp_python.egg-info/PKG-INFO
writing dependency_links to llama_cpp_python.egg-info/dependency_links.txt
writing requirements to llama_cpp_python.egg-info/requires.txt
writing top-level names to llama_cpp_python.egg-info/top_level.txt
reading manifest file 'llama_cpp_python.egg-info/SOURCES.txt'
adding license file 'LICENSE.md'
writing manifest file 'llama_cpp_python.egg-info/SOURCES.txt'
running build_ext
Creating /home/mulderg/anaconda3/envs/lcp/lib/python3.10/site-packages/llama-cpp-python.egg-link (link to .)
llama-cpp-python 0.1.34 is already the active version in easy-install.pth

Installed /home/mulderg/Work/llama-cpp-python
Processing dependencies for llama-cpp-python==0.1.34
Searching for typing-extensions==4.5.0
Best match: typing-extensions 4.5.0
Processing typing_extensions-4.5.0-py3.10.egg
typing-extensions 4.5.0 is already the active version in easy-install.pth

Using /home/mulderg/anaconda3/envs/lcp/lib/python3.10/site-packages/typing_extensions-4.5.0-py3.10.egg
Finished processing dependencies for llama-cpp-python==0.1.34

$ HOST=192.168.1.73 python3 -m llama_cpp.server
Traceback (most recent call last):
  File "/home/mulderg/anaconda3/envs/lcp/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/mulderg/anaconda3/envs/lcp/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/mulderg/Work/llama-cpp-python/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/home/mulderg/Work/llama-cpp-python/llama_cpp/llama_cpp.py", line 192, in <module>
    _lib.llama_apply_lora_from_file.argtypes = [llama_context_p, c_char_p, c_char_p, c_int]
  File "/home/mulderg/anaconda3/envs/lcp/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/home/mulderg/anaconda3/envs/lcp/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/mulderg/Work/llama-cpp-python/llama_cpp/libllama.so: undefined symbol: llama_apply_lora_from_file

```

**Comment by abetlen** [comment]
@gjmulder seems like it's failing to install after building, can you run `readelf -Ws --dyn-syms /path/to/libllama.so | grep apply_lora` and make sure it doesn't return anything.

**Comment by gjmulder** [comment]
```
$ for X in `find . -name libllama.so`; do echo $X; readelf -Ws --dyn-syms $X | grep -c apply_lora; done
./vendor/llama.cpp/libllama.so
0
./llama_cpp/libllama.so
0
./_skbuild/linux-x86_64-3.10/cmake-install/llama_cpp/libllama.so
0

```

**Comment by horenbergerb** [comment]
This came out in the newest version, right? I used it earlier and it seemed to be working fine.

**Comment by abetlen** [comment]
@horenbergerb thanks! I'll close this issue in that case.
