### ISSUE TITLE
Llava/CLIP Models Not Loading Properly

### ISSUE THREAD

**Issue by JoshuaFurman** [abetlen/llama-cpp-python#946]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Llava should be loading however following the README example I am getting the following error:
`clip_model_load: total allocated memory: 195.95 MB
Traceback (most recent call last):
  File "/Users/furm/projects/watcher/main.py", line 26, in <module>
    llm.create_chat_completion(
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/llama.py", line 2017, in create_chat_completion
    return handler(
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/llama_chat_format.py", line 1049, in __call__
    assert (
AssertionError
Exception ignored in: <function Llava15ChatHandler.__del__ at 0x105d1cf70>
Traceback (most recent call last):
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/llama_chat_format.py", line 996, in __del__
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/_utils.py", line 20, in __enter__
LookupError: unknown encoding: ascii
ggml_metal_free: deallocating`

I'm really not too sure what I'm doing wrong... I'm using the code directly from the README, Both the CLIP model and Llava model are in .gguf format.

# Environment and Context

Using a M2 Macbook Air, Python 3.9.6.

**Comment by D4ve-R** [comment]
@JoshuaFurman, try running it with this model:
* [model](https://huggingface.co/mys/ggml_bakllava-1/resolve/main/ggml-model-q4_k.gguf)
* [clip_model](https://huggingface.co/mys/ggml_bakllava-1/resolve/main/mmproj-model-f16.gguf)

your clip model file seems to be in the wrong encoding and too small in comparison to other clip models

**Comment by JoshuaFurman** [comment]
Thanks for the suggestion @D4ve-R. Just downloaded those models and I'm seeing the same errors:
`objc[84786]: Class GGMLMetalClass is implemented in both /Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/libllama.dylib (0x1009a8228) and /Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/libllava.dylib (0x10267c228). One of the two will be used. Which one is undefined.
Exception ignored in: <function Llava15ChatHandler.__del__ at 0x1012adf70>
Traceback (most recent call last):
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/llama_chat_format.py", line 996, in __del__
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/_utils.py", line 20, in __enter__
LookupError: unknown encoding: ascii
Exception ignored in: <function _LlamaModel.__del__ at 0x102413d30>
Traceback (most recent call last):
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/llama.py", line 240, in __del__
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/_utils.py", line 20, in __enter__
LookupError: unknown encoding: ascii
Exception ignored in: <function _LlamaContext.__del__ at 0x102417ca0>
Traceback (most recent call last):
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/llama.py", line 422, in __del__
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/_utils.py", line 20, in __enter__
LookupError: unknown encoding: ascii
Exception ignored in: <function _LlamaBatch.__del__ at 0x10241c040>
Traceback (most recent call last):
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/llama.py", line 670, in __del__
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/_utils.py", line 20, in __enter__
LookupError: unknown encoding: ascii
clip_model_load: total allocated memory: 195.95 MB

encode_image_with_clip: image encoded in  1928.89 ms by CLIP (    3.35 ms per image patch)`

Possibly my implementation may be wrong? 

`from llama_cpp import Llama
from llama_cpp.llama_chat_format import Llava15ChatHandler
import base64

def image_to_base64_data_uri(file_path):
    with open(file_path, "rb") as img_file:
        base64_data = base64.b64encode(img_file.read()).decode('utf-8')
        return f"data:image/png;base64,{base64_data}"


file_path = '/Users/furm/projects/llama.cpp/llava-stuff/selfie.png'
data_uri = image_to_base64_data_uri(file_path)

### Test
clip_model_path = "models/mmproj-model-f16.gguf"
model_path = "models/ggml-model-q4_k.gguf"

chat_handler = Llava15ChatHandler(clip_model_path=clip_model_path)
llm = Llama(
    model_path = model_path,
    chat_format = "llava-1-5",
    chat_handler = chat_handler,
    n_ctx = 2048, # n_ctx should be increased to accomodate the image embedding
    n_gpu_layers = 1,
    logits_all = True,
    verbose = False
)

llm.create_chat_completion(
    messages=[
        {"role": "system", "content": "You are an assistant who perfectly describes images."},
        {
            "role": "user",
            "content": [
                {"type": "image_url", "image_url": {"url": data_uri}},
                {"type": "text", "text": "Describe this image in detail please."}
            ]
        }
    ]
)`

**Comment by JoshuaFurman** [comment]
Funny enough I just tested a simple inference with openhermes-2.5-mistral7b and the inference completes but I'm still being thrown the `LookupError: unknown encoding: ascii`...

Code:
```
from llama_cpp import Llama

llm = Llama(model_path="./models/openhermes/openhermes-2.5-mistral-7b.Q5_K_M.gguf", n_gpu_layers=1, verbose = False)
output = llm(
    "Name the planets in the solar system? ",  # Prompt
    echo = True  # Echo the prompt back in the output
)

print(output)
```

**Comment by D4ve-R** [comment]
What happens when you run with `n_gpu_layers = 0`?

**Comment by tk-master** [comment]
I tested the code and I got no errors on windows, seems like an issue on mac

**Comment by D4ve-R** [comment]
It works fine on a 2018 intel MacBook Pro

**Comment by abetlen** [comment]
Hey @JoshuaFurman not sure the cause of this issue but 2 things that stand out:

1. `objc[84786]: Class GGMLMetalClass is implemented in both /Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/libllama.dylib (0x1009a8228) and /Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/libllava.dylib (0x10267c228). One of the two will be used. Which one is undefined.` this implies some issue with how we're building both llama and llava as shared libraries.
2. `Traceback (most recent call last):
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/llama_chat_format.py", line 996, in __del__
  File "/Users/furm/projects/watcher/venv/lib/python3.9/site-packages/llama_cpp/_utils.py", line 20, in __enter__
LookupError: unknown encoding: ascii` this is an error with the stdout / stderr capture, can you rerun with `verbose=True`?

**Comment by sweetcard** [comment]
> ```python
> verbose = False
> ```

remove this line :

`verbose = False`

It works again. 😄

**Comment by W1nterFloW** [comment]
I have the similar problem, when I use code below to load llama model:
`llm = Llama(model_path="./models/llama-2-7b-chat.Q4_K_M.gguf", verbose=False, n_gpu_layers=30)`
Then an exception will be throwed:

> Exception ignored in: <function _LlamaContext.__del__ at 0x7f69f2214c10>
Traceback (most recent call last):
  File "/home/lwc/anaconda3/envs/gpu_llama/lib/python3.9/site-packages/llama_cpp/llama.py", line 425, in __del__
  File "/home/lwc/anaconda3/envs/gpu_llama/lib/python3.9/site-packages/llama_cpp/_utils.py", line 24, in __enter__
LookupError: unknown encoding: ascii
Exception ignored in: <function _LlamaModel.__del__ at 0x7f69f2212ca0>
Traceback (most recent call last):
  File "/home/lwc/anaconda3/envs/gpu_llama/lib/python3.9/site-packages/llama_cpp/llama.py", line 241, in __del__
  File "/home/lwc/anaconda3/envs/gpu_llama/lib/python3.9/site-packages/llama_cpp/_utils.py", line 24, in __enter__
LookupError: unknown encoding: ascii
Exception ignored in: <function _LlamaBatch.__del__ at 0x7f69f2216f70>
Traceback (most recent call last):
  File "/home/lwc/anaconda3/envs/gpu_llama/lib/python3.9/site-packages/llama_cpp/llama.py", line 675, in __del__
  File "/home/lwc/anaconda3/envs/gpu_llama/lib/python3.9/site-packages/llama_cpp/_utils.py", line 24, in __enter__
LookupError: unknown encoding: ascii

problem will not occur when `verbose=True`

**Comment by zoldaten** [comment]
i have the same problem on windows 10:
```
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2447.45 ms
llama_print_timings:      sample time =      22.66 ms /   104 runs   (    0.22 ms per token,  4589.79 tokens per second)
llama_print_timings: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_print_timings:        eval time =   18997.99 ms /   104 runs   (  182.67 ms per token,     5.47 tokens per second)
llama_print_timings:       total time =   19263.97 ms /   105 tokens
Exception ignored in: <function Llava15ChatHandler.__del__ at 0x0000026845EBCF70>
Traceback (most recent call last):
  File "C:\Users\{}\.pyenv\pyenv-win\versions\3.10.9\lib\site-packages\llama_cpp\llama_chat_format.py", line 2171, in __del__
  File "C:\Users\{}\.pyenv\pyenv-win\versions\3.10.9\lib\site-packages\llama_cpp\_utils.py", line 38, in __enter__
ValueError: I/O operation on closed file
```

verbose=True or verbose=False doesnt fix it.
