### ISSUE TITLE
The llama-cpp-python installed using the following method cannot find llama.dll, but the actual llama.dll exists.

### ISSUE THREAD

**Issue by chengjia604** [abetlen/llama-cpp-python#981]
**installation method：**
https://github.com/lperezmo/clblast-llama-cpp-python
**Download llama_cpp_python：**
![image](https://github.com/abetlen/llama-cpp-python/assets/63001991/77d3273e-e479-492a-8231-9d62cfdf6a64)
**error:**
Traceback (most recent call last):
  File "d:\python\Lib\site-packages\llama_cpp\llama_cpp.py", line 72, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'd:\python\Lib\site-packages\llama_cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python\Lib\site-packages\llama_cpp\llama_cpp.py", line 86, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python\Lib\site-packages\llama_cpp\llama_cpp.py", line 75, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library 'd:\python\Lib\site-packages\llama_cpp\llama.dll': Could not find module 'd:\python\Lib\site-packages\llama_cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by abetlen** [comment]
@jreves that's correct, it's likely a dependency. If you check out llama_cpp.py line 58 actually adds the `CUDA_PATH` as a dll search directory, not sure if AMD has a similar common path variable but would be happy to add it if it helps.

**Comment by jreves** [comment]
@abetlen , yes there's a similar path for HIP installs on native Windows. The HIP directory is available as %HIP_PATH%, and the libraries are in %HIP_PATH$lib. The utilities - including the clang and clang++ compilers are in %HIP_PATH%bin.

%HIP_PATH% references the specific version as a part of the directory structure, so on my system - for example - %HIP_PATH$ expands to C:\Program Files\AMD\ROCm\5.5\.  The hipblas.dll file is in the bin directory.

There's a useful utility in the bin directory, as well: hipinfo.exe.  Here's an example of the output:
c:\Program Files\AMD\ROCm\5.5\bin>hipinfo

--------------------------------------------------------------------------------
device#                           0
Name:                             AMD Radeon RX 6900 XT
pciBusID:                         47
pciDeviceID:                      0
pciDomainID:                      0
multiProcessorCount:              40
maxThreadsPerMultiProcessor:      2048
isMultiGpuBoard:                  0
clockRate:                        2105 Mhz
memoryClockRate:                  1000 Mhz
memoryBusWidth:                   0
totalGlobalMem:                   15.98 GB
totalConstMem:                    2147483647
sharedMemPerBlock:                64.00 KB
canMapHostMemory:                 1
regsPerBlock:                     0
warpSize:                         32
l2CacheSize:                      4194304
computeMode:                      0
maxThreadsPerBlock:               1024
maxThreadsDim.x:                  1024
maxThreadsDim.y:                  1024
maxThreadsDim.z:                  1024
maxGridSize.x:                    2147483647
maxGridSize.y:                    65536
maxGridSize.z:                    65536
major:                            10
minor:                            3
concurrentKernels:                1
cooperativeLaunch:                0
cooperativeMultiDeviceLaunch:     0
isIntegrated:                     0
maxTexture1D:                     16384
maxTexture2D.width:               16384
maxTexture2D.height:              16384
maxTexture3D.width:               2048
maxTexture3D.height:              2048
maxTexture3D.depth:               2048
isLargeBar:                       0
asicRevision:                     0
maxSharedMemoryPerMultiProcessor: 64.00 KB
clockInstructionRate:             1000.00 Mhz
arch.hasGlobalInt32Atomics:       1
arch.hasGlobalFloatAtomicExch:    1
arch.hasSharedInt32Atomics:       1
arch.hasSharedFloatAtomicExch:    1
arch.hasFloatAtomicAdd:           1
arch.hasGlobalInt64Atomics:       1
arch.hasSharedInt64Atomics:       1
arch.hasDoubles:                  1
arch.hasWarpVote:                 1
arch.hasWarpBallot:               1
arch.hasWarpShuffle:              1
arch.hasFunnelShift:              0
arch.hasThreadFenceSystem:        1
arch.hasSyncThreadsExt:           0
arch.hasSurfaceFuncs:             0
arch.has3dGrid:                   1
arch.hasDynamicParallelism:       0
gcnArchName:                      gfx1030
peers:
non-peers:                        device#0

memInfo.total:                    15.98 GB
memInfo.free:                     15.86 GB (99%)

**Comment by abetlen** [comment]
@jreves perfect, I've added `HIP_PATH` to the dll search directories for windows users if it's defined in their environment. Should be in the next release

**Comment by abetlen** [comment]
@chengjia604 does that resolve your issue as well?

**Comment by QQCif** [comment]
I tried to use the prebuilt binary provided by llama.cpp repo. After setting ```LLAMA_CPP_LIB``` to the path of ```llama.dll``` I am getting the same error. ```cublas64_12.dll```, ```cublasLt64_12```, ```cudart64_12.dll``` are all present in the same folder as ```llama.dll```. However if I tried to add llama.cpp binary folder to ```PATH```, then it works.

**Comment by brockhager** [comment]
I'm having this same issue. 

Here is the error I get:
02:08:15:llama_chat_adapter.py:     from .llama_cpp import *
02:08:15:llama_chat_adapter.py:   File "C:\Program Files\CodeProject\AI\modules\LlamaChat\bin\windows\python311\venv\lib\site-packages\llama_cpp\llama_cpp.py", line 88, in 
02:08:15:llama_chat_adapter.py:     _lib = _load_shared_library(_lib_base_name)
02:08:15:llama_chat_adapter.py:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:08:15:llama_chat_adapter.py:   File "C:\Program Files\CodeProject\AI\modules\LlamaChat\bin\windows\python311\venv\lib\site-packages\llama_cpp\llama_cpp.py", line 77, in _load_shared_library
02:08:15:llama_chat_adapter.py:     raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
02:08:15:llama_chat_adapter.py: RuntimeError: Failed to load shared library 'C:\Program Files\CodeProject\AI\modules\LlamaChat\bin\windows\python311\venv\lib\site-packages\llama_cpp\lib\llama.dll': Could not find module 'C:\Program Files\CodeProject\AI\modules\LlamaChat\bin\windows\python311\venv\lib\site-packages\llama_cpp\lib\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.
02:08:15:Module LlamaChat has shutdown

Local install on Win10 OS

**Comment by ajinkya123-robo** [comment]
Any update on this issue?  I am facing same error. Kindly guide. Thanks
